### ISSUE TITLE
Problems with "fit function to data" widget

### ISSUE THREAD

**Issue by g-sob** [veusz/veusz#213]
Dear Jeremy, 

I couldn't fit a simple linear eq to a 5 points x,y dataset. I would like to plot the line y = 1.5177*x with the x,y dispersion (data below), but the below message keeps showing up.
Not sure what I'm doing wrong.

x	x_err	y	y_err
0	0	0	0
54.57	1.79	545.42	23.65
146.21	5.16	559.53	9.32
457.52	12.12	1001.28	63.8
1041.8	8.01	1374.71	32.77

Please help :)

 Welcome 

to Veusz 1.27 --- a scientific plotting application.
Copyright © 2003-2017 Jeremy Sanders <jeremy@jeremysanders.net> and contributors.
Veusz comes with ABSOLUTELY NO WARRANTY. Veusz is Free Software, and you are
welcome to redistribute it under certain conditions. Enter "GPL()" for details.
This window is a Python command line console and acts as a calculator.
Fitting via Minuit:
C:\PROGRA~1\Veusz\veusz\widgets\fit.py:56: RuntimeWarning: invalid value encountered in true_divide
    1      nan        0   1.5177 
    2      nan      nan   1.5177 
    3      nan      nan   1.5177 
    4      nan      nan   1.5177 
    5      nan      nan   1.5177 
    6      nan      nan   1.5177 
    7      nan      nan   1.5177 
    8      nan        0      nan 
    9      nan        0      nan 
   10      nan        0      nan 
   11      nan        0      nan 
   12      nan        0      nan 
   13      nan        0      nan 
   14      nan      nan      nan 
   15      nan      nan      nan 
   16      nan      nan      nan 
   17      nan      nan      nan 
   18      nan      nan      nan 
   19      nan      nan      nan 
   20      nan      nan      nan 
   21      nan      nan      nan 
   22      nan      nan      nan 
   23      nan      nan      nan 
   24      nan      nan      nan 
   25      nan      nan      nan 
   26      nan      nan      nan 
   27      nan      nan      nan 
   28      nan      nan      nan 
   29      nan      nan      nan 
   30      nan      nan      nan 
   31      nan      nan      nan 
   32      nan      nan      nan 
   33      nan      nan      nan 
   34      nan      nan      nan 
   35      nan      nan      nan 
   36      nan      nan      nan 
   37      nan      nan      nan 
   38      nan      nan      nan 
   39      nan      nan      nan 
MINOS failed.
Fit results:
    a = nan ± nan
    b = nan ± nan
MINOS error estimate not available.
chi^2 = nan, dof = 3, reduced-chi^2 = nan
Traceback (most recent call last):
  File "C:\src\veusz-msvc\veusz\build\veusz_windows_pyinst\out00-PYZ.pyz\veusz.windows.consolewindow", line 258, in runFunction
  File "C:\src\veusz-msvc\veusz\build\veusz_windows_pyinst\out00-PYZ.pyz\veusz.widgets.fit", line 379, in actionFit
  File "C:\src\veusz-msvc\veusz\build\veusz_windows_pyinst\out00-PYZ.pyz\veusz.document.doc", line 171, in applyOperation
  File "C:\src\veusz-msvc\veusz\build\veusz_windows_pyinst\out00-PYZ.pyz\veusz.document.operations", line 1149, in do
  File "C:\src\veusz-msvc\veusz\build\veusz_windows_pyinst\out00-PYZ.pyz\veusz.document.operations", line 83, in do
  File "C:\src\veusz-msvc\veusz\build\veusz_windows_pyinst\out00-PYZ.pyz\veusz.setting.setting", line 133, in set
  File "C:\src\veusz-msvc\veusz\build\veusz_windows_pyinst\out00-PYZ.pyz\veusz.setting.setting", line 560, in convertTo
  File "C:\src\veusz-msvc\veusz\build\veusz_windows_pyinst\out00-PYZ.pyz\veusz.setting.setting", line 526, in _finiteRangeFloat
InvalidType: Finite values only allowed
Error evaluating expression in function widget 'fit1': 'name 'x' is not defined'
Error evaluating expression in function widget 'fit1': 'name 'x' is not defined'
Traceback (most recent call last):
  File "C:\src\veusz-msvc\veusz\build\veusz_windows_pyinst\out00-PYZ.pyz\veusz.windows.consolewindow", line 258, in runFunction
  File "C:\src\veusz-msvc\veusz\build\veusz_windows_pyinst\out00-PYZ.pyz\veusz.widgets.fit", line 257, in actionFit
AttributeError: 'NoneType' object has no attribute 'data'
Fitting x from 0 to 1200
Fitting via Minuit:
    1      nan        0   1.5177 
    2      nan      nan   1.5177 
    3      nan      nan   1.5177 
    4      nan      nan   1.5177 
    5      nan      nan   1.5177 
    6      nan      nan   1.5177 
    7      nan      nan   1.5177 
    8      nan        0      nan 
    9      nan        0      nan 
   10      nan        0      nan 
   11      nan        0      nan 
   12      nan        0      nan 
   13      nan        0      nan 
   14      nan      nan      nan 
   15      nan      nan      nan 
   16      nan      nan      nan 
   17      nan      nan      nan 
   18      nan      nan      nan 
   19      nan      nan      nan 
   20      nan      nan      nan 
   21      nan      nan      nan 
   22      nan      nan      nan 
   23      nan      nan      nan 
   24      nan      nan      nan 
   25      nan      nan      nan 
   26      nan      nan      nan 
   27      nan      nan      nan 
   28      nan      nan      nan 
   29      nan      nan      nan 
   30      nan      nan      nan 
   31      nan      nan      nan 
   32      nan      nan      nan 
   33      nan      nan      nan 
   34      nan      nan      nan 
   35      nan      nan      nan 
   36      nan      nan      nan 
   37      nan      nan      nan 
   38      nan      nan      nan 
   39      nan      nan      nan 
MINOS failed.
Fit results:
    a = nan ± nan
    b = nan ± nan
MINOS error estimate not available.
chi^2 = nan, dof = 3, reduced-chi^2 = nan
Traceback (most recent call last):
  File "C:\src\veusz-msvc\veusz\build\veusz_windows_pyinst\out00-PYZ.pyz\veusz.windows.consolewindow", line 258, in runFunction
  File "C:\src\veusz-msvc\veusz\build\veusz_windows_pyinst\out00-PYZ.pyz\veusz.widgets.fit", line 379, in actionFit
  File "C:\src\veusz-msvc\veusz\build\veusz_windows_pyinst\out00-PYZ.pyz\veusz.document.doc", line 171, in applyOperation
  File "C:\src\veusz-msvc\veusz\build\veusz_windows_pyinst\out00-PYZ.pyz\veusz.document.operations", line 1149, in do
  File "C:\src\veusz-msvc\veusz\build\veusz_windows_pyinst\out00-PYZ.pyz\veusz.document.operations", line 83, in do
  File "C:\src\veusz-msvc\veusz\build\veusz_windows_pyinst\out00-PYZ.pyz\veusz.setting.setting", line 133, in set
  File "C:\src\veusz-msvc\veusz\build\veusz_windows_pyinst\out00-PYZ.pyz\veusz.setting.setting", line 560, in convertTo
  File "C:\src\veusz-msvc\veusz\build\veusz_windows_pyinst\out00-PYZ.pyz\veusz.setting.setting", line 526, in _finiteRangeFloat
InvalidType: Finite values only allowed
Fitting x from 0 to 1200
Fitting via Minuit:
    1      nan        0   1.5177 
    2      nan      nan   1.5177 
    3      nan      nan   1.5177 
    4      nan      nan   1.5177 
    5      nan      nan   1.5177 
    6      nan      nan   1.5177 
    7      nan      nan   1.5177 
    8      nan        0      nan 
    9      nan        0      nan 
   10      nan        0      nan 
   11      nan        0      nan 
   12      nan        0      nan 
   13      nan        0      nan 
   14      nan      nan      nan 
   15      nan      nan      nan 
   16      nan      nan      nan 
   17      nan      nan      nan 
   18      nan      nan      nan 
   19      nan      nan      nan 
   20      nan      nan      nan 
   21      nan      nan      nan 
   22      nan      nan      nan 
   23      nan      nan      nan 
   24      nan      nan      nan 
   25      nan      nan      nan 
   26      nan      nan      nan 
   27      nan      nan      nan 
   28      nan      nan      nan 
   29      nan      nan      nan 
   30      nan      nan      nan 
   31      nan      nan      nan 
   32      nan      nan      nan 
   33      nan      nan      nan 
   34      nan      nan      nan 
   35      nan      nan      nan 
   36      nan      nan      nan 
   37      nan      nan      nan 
   38      nan      nan      nan 
   39      nan      nan      nan 
MINOS failed.
Fit results:
    a = nan ± nan
    b = nan ± nan
MINOS error estimate not available.
chi^2 = nan, dof = 3, reduced-chi^2 = nan
Traceback (most recent call last):
  File "C:\src\veusz-msvc\veusz\build\veusz_windows_pyinst\out00-PYZ.pyz\veusz.windows.consolewindow", line 258, in runFunction
  File "C:\src\veusz-msvc\veusz\build\veusz_windows_pyinst\out00-PYZ.pyz\veusz.widgets.fit", line 379, in actionFit
  File "C:\src\veusz-msvc\veusz\build\veusz_windows_pyinst\out00-PYZ.pyz\veusz.document.doc", line 171, in applyOperation
  File "C:\src\veusz-msvc\veusz\build\veusz_windows_pyinst\out00-PYZ.pyz\veusz.document.operations", line 1149, in do
  File "C:\src\veusz-msvc\veusz\build\veusz_windows_pyinst\out00-PYZ.pyz\veusz.document.operations", line 83, in do
  File "C:\src\veusz-msvc\veusz\build\veusz_windows_pyinst\out00-PYZ.pyz\veusz.setting.setting", line 133, in set
  File "C:\src\veusz-msvc\veusz\build\veusz_windows_pyinst\out00-PYZ.pyz\veusz.setting.setting", line 560, in convertTo
  File "C:\src\veusz-msvc\veusz\build\veusz_windows_pyinst\out00-PYZ.pyz\veusz.setting.setting", line 526, in _finiteRangeFloat
InvalidType: Finite values only allowed
Error in expression 'y = a + b*x': Unable to parse file: invalid syntax (<string>, line 1)
Error in expression 'y = a + b*x': Unable to parse file: invalid syntax (<string>, line 1)
Error in expression 'y = a + b*x': Unable to parse file: invalid syntax (<string>, line 1)
Fitting via Minuit:
    1      nan        0   1.5177 
    2      nan      nan   1.5177 
    3      nan      nan   1.5177 
    4      nan      nan   1.5177 
    5      nan      nan   1.5177 
    6      nan      nan   1.5177 
    7      nan      nan   1.5177 
    8      nan        0      nan 
    9      nan        0      nan 
   10      nan        0      nan 
   11      nan        0      nan 
   12      nan        0      nan 
   13      nan        0      nan 
   14      nan      nan      nan 
   15      nan      nan      nan 
   16      nan      nan      nan 
   17      nan      nan      nan 
   18      nan      nan      nan 
   19      nan      nan      nan 
   20      nan      nan      nan 
   21      nan      nan      nan 
   22      nan      nan      nan 
   23      nan      nan      nan 
   24      nan      nan      nan 
   25      nan      nan      nan 
   26      nan      nan      nan 
   27      nan      nan      nan 
   28      nan      nan      nan 
   29      nan      nan      nan 
   30      nan      nan      nan 
   31      nan      nan      nan 
   32      nan      nan      nan 
   33      nan      nan      nan 
   34      nan      nan      nan 
   35      nan      nan      nan 
   36      nan      nan      nan 
   37      nan      nan      nan 
   38      nan      nan      nan 
   39      nan      nan      nan 
MINOS failed.
Fit results:
    a = nan ± nan
    b = nan ± nan
MINOS error estimate not available.
chi^2 = nan, dof = 3, reduced-chi^2 = nan
Traceback (most recent call last):
  File "C:\src\veusz-msvc\veusz\build\veusz_windows_pyinst\out00-PYZ.pyz\veusz.windows.consolewindow", line 258, in runFunction
  File "C:\src\veusz-msvc\veusz\build\veusz_windows_pyinst\out00-PYZ.pyz\veusz.widgets.fit", line 379, in actionFit
  File "C:\src\veusz-msvc\veusz\build\veusz_windows_pyinst\out00-PYZ.pyz\veusz.document.doc", line 171, in applyOperation
  File "C:\src\veusz-msvc\veusz\build\veusz_windows_pyinst\out00-PYZ.pyz\veusz.document.operations", line 1149, in do
  File "C:\src\veusz-msvc\veusz\build\veusz_windows_pyinst\out00-PYZ.pyz\veusz.document.operations", line 83, in do
  File "C:\src\veusz-msvc\veusz\build\veusz_windows_pyinst\out00-PYZ.pyz\veusz.setting.setting", line 133, in set
  File "C:\src\veusz-msvc\veusz\build\veusz_windows_pyinst\out00-PYZ.pyz\veusz.setting.setting", line 560, in convertTo
  File "C:\src\veusz-msvc\veusz\build\veusz_windows_pyinst\out00-PYZ.pyz\veusz.setting.setting", line 526, in _finiteRangeFloat
InvalidType: Finite values only allowed
Fitting via Minuit:
    1      nan      nan      nan 
    2      nan      nan      nan 
    3      nan      nan      nan 
    4      nan      nan      nan 
    5      nan      nan      nan 
    6      nan      nan      nan 
    7      nan      nan      nan 
    8      nan      nan      nan 
    9      nan      nan      nan 
   10      nan      nan      nan 
   11      nan      nan      nan 
   12      nan      nan      nan 
   13      nan      nan      nan 
   14      nan      nan      nan 
   15      nan      nan      nan 
   16      nan      nan      nan 
   17      nan      nan      nan 
   18      nan      nan      nan 
   19      nan      nan      nan 
   20      nan      nan      nan 
   21      nan      nan      nan 
   22      nan      nan      nan 
   23      nan      nan      nan 
   24      nan      nan      nan 
   25      nan      nan      nan 
   26      nan      nan      nan 
   27      nan      nan      nan 
   28      nan      nan      nan 
   29      nan      nan      nan 
   30      nan      nan      nan 
   31      nan      nan      nan 
   32      nan      nan      nan 
   33      nan      nan      nan 
   34      nan      nan      nan 
   35      nan      nan      nan 
   36      nan      nan      nan 
   37      nan      nan      nan 
   38      nan      nan      nan 
   39      nan      nan      nan 
MINOS failed.
Fit results:
    a = nan ± nan
    b = nan ± nan
MINOS error estimate not available.
chi^2 = nan, dof = 3, reduced-chi^2 = nan
Traceback (most recent call last):
  File "C:\src\veusz-msvc\veusz\build\veusz_windows_pyinst\out00-PYZ.pyz\veusz.windows.consolewindow", line 258, in runFunction
  File "C:\src\veusz-msvc\veusz\build\veusz_windows_pyinst\out00-PYZ.pyz\veusz.widgets.fit", line 379, in actionFit
  File "C:\src\veusz-msvc\veusz\build\veusz_windows_pyinst\out00-PYZ.pyz\veusz.document.doc", line 171, in applyOperation
  File "C:\src\veusz-msvc\veusz\build\veusz_windows_pyinst\out00-PYZ.pyz\veusz.document.operations", line 1149, in do
  File "C:\src\veusz-msvc\veusz\build\veusz_windows_pyinst\out00-PYZ.pyz\veusz.document.operations", line 83, in do
  File "C:\src\veusz-msvc\veusz\build\veusz_windows_pyinst\out00-PYZ.pyz\veusz.setting.setting", line 133, in set
  File "C:\src\veusz-msvc\veusz\build\veusz_windows_pyinst\out00-PYZ.pyz\veusz.setting.setting", line 560, in convertTo
  File "C:\src\veusz-msvc\veusz\build\veusz_windows_pyinst\out00-PYZ.pyz\veusz.setting.setting", line 526, in _finiteRangeFloat
InvalidType: Finite values only allowed
Fitting via Minuit:
    1      nan      nan      nan 
    2      nan      nan      nan 
    3      nan      nan      nan 
    4      nan      nan      nan 
    5      nan      nan      nan 
    6      nan      nan      nan 
    7      nan      nan      nan 
    8      nan      nan      nan 
    9      nan      nan      nan 
   10      nan      nan      nan 
   11      nan      nan      nan 
   12      nan      nan      nan 
   13      nan      nan      nan 
   14      nan      nan      nan 
   15      nan      nan      nan 
   16      nan      nan      nan 
   17      nan      nan      nan 
   18      nan      nan      nan 
   19      nan      nan      nan 
   20      nan      nan      nan 
   21      nan      nan      nan 
   22      nan      nan      nan 
   23      nan      nan      nan 
   24      nan      nan      nan 
   25      nan      nan      nan 
   26      nan      nan      nan 
   27      nan      nan      nan 
   28      nan      nan      nan 
   29      nan      nan      nan 
   30      nan      nan      nan 
   31      nan      nan      nan 
   32      nan      nan      nan 
   33      nan      nan      nan 
   34      nan      nan      nan 
   35      nan      nan      nan 
   36      nan      nan      nan 
   37      nan      nan      nan 
   38      nan      nan      nan 
   39      nan      nan      nan 
MINOS failed.
Fit results:
    a = nan ± nan
    b = nan ± nan
MINOS error estimate not available.
chi^2 = nan, dof = 3, reduced-chi^2 = nan
Traceback (most recent call last):
  File "C:\src\veusz-msvc\veusz\build\veusz_windows_pyinst\out00-PYZ.pyz\veusz.windows.consolewindow", line 258, in runFunction
  File "C:\src\veusz-msvc\veusz\build\veusz_windows_pyinst\out00-PYZ.pyz\veusz.widgets.fit", line 379, in actionFit
  File "C:\src\veusz-msvc\veusz\build\veusz_windows_pyinst\out00-PYZ.pyz\veusz.document.doc", line 171, in applyOperation
  File "C:\src\veusz-msvc\veusz\build\veusz_windows_pyinst\out00-PYZ.pyz\veusz.document.operations", line 1149, in do
  File "C:\src\veusz-msvc\veusz\build\veusz_windows_pyinst\out00-PYZ.pyz\veusz.document.operations", line 83, in do
  File "C:\src\veusz-msvc\veusz\build\veusz_windows_pyinst\out00-PYZ.pyz\veusz.setting.setting", line 133, in set
  File "C:\src\veusz-msvc\veusz\build\veusz_windows_pyinst\out00-PYZ.pyz\veusz.setting.setting", line 560, in convertTo
  File "C:\src\veusz-msvc\veusz\build\veusz_windows_pyinst\out00-PYZ.pyz\veusz.setting.setting", line 526, in _finiteRangeFloat
InvalidType: Finite values only allowed
Fitting via Minuit:
    1      nan   1.5177 
    2      nan      nan 
    3      nan      nan 
    4      nan      nan 
    5      nan      nan 
    6      nan      nan 
    7      nan      nan 
    8      nan      nan 
    9      nan      nan 
   10      nan      nan 
   11      nan      nan 
   12      nan      nan 
   13      nan      nan 
   14      nan      nan 
   15      nan      nan 
   16      nan      nan 
   17      nan      nan 
   18      nan      nan 
   19      nan      nan 
   20      nan      nan 
   21      nan      nan 
   22      nan      nan 
   23      nan      nan 
   24      nan      nan 
   25      nan      nan 
   26      nan      nan 
   27      nan      nan 
MINOS failed.
Fit results:
    b = nan ± nan
MINOS error estimate not available.
chi^2 = nan, dof = 4, reduced-chi^2 = nan
Traceback (most recent call last):
  File "C:\src\veusz-msvc\veusz\build\veusz_windows_pyinst\out00-PYZ.pyz\veusz.windows.consolewindow", line 258, in runFunction
  File "C:\src\veusz-msvc\veusz\build\veusz_windows_pyinst\out00-PYZ.pyz\veusz.widgets.fit", line 379, in actionFit
  File "C:\src\veusz-msvc\veusz\build\veusz_windows_pyinst\out00-PYZ.pyz\veusz.document.doc", line 171, in applyOperation
  File "C:\src\veusz-msvc\veusz\build\veusz_windows_pyinst\out00-PYZ.pyz\veusz.document.operations", line 1149, in do
  File "C:\src\veusz-msvc\veusz\build\veusz_windows_pyinst\out00-PYZ.pyz\veusz.document.operations", line 83, in do
  File "C:\src\veusz-msvc\veusz\build\veusz_windows_pyinst\out00-PYZ.pyz\veusz.setting.setting", line 133, in set
  File "C:\src\veusz-msvc\veusz\build\veusz_windows_pyinst\out00-PYZ.pyz\veusz.setting.setting", line 560, in convertTo
  File "C:\src\veusz-msvc\veusz\build\veusz_windows_pyinst\out00-PYZ.pyz\veusz.setting.setting", line 526, in _finiteRangeFloat
InvalidType: Finite values only allowed

**Comment by jeremysanders** [comment]
It's failing because you have a point with a zero error bar. The chi2 value of the fit will be infinite.

**Comment by g-sob** [comment]
Oh, I see. Would there be a way to fit the date only by means of R^2 and/or SSE? (I have done the regression with another stats package and I have already plotted the graph I need with the "plot a function" widget, thank you once more for the great program!!).

:)

**Comment by jeremysanders** [comment]
Unfortunately that's all there is. The fitting could be more flexible. You can force the error bar in your fitting to be constant or have a minimum error, i.e. change y data on the fit widget to be:

    x, 0.1

or

    x, clip(x_serr, 0.1, None)

**Comment by bhanudaysharma** [comment]
I also faced a similar error. I wanted to fit the data in Y = exp(a X). But the curve-fitting procedure failed. Even if I start the fitting with a perfect initial guess (in this case, it is Y = exp(1.9*X), the curve-fit solution diverges. Please see the attached image and data file. What is the reason? Is there any way to improve the fitting in veusz framework? Maybe, if the Scikit-Learns' curvefit function can be imported in veusz, that would improve the robustness of the fitting in Veusz. Thanks for such an awesome program! 

![image](https://user-images.githubusercontent.com/55601693/150089090-09a8d431-6023-4108-8d4a-d47355bbb78f.png)
[Exponential-Fit-graph-data-Copy.txt](https://github.com/veusz/veusz/files/7895184/Exponential-Fit-graph-data-Copy.txt)
