### ISSUE TITLE
FITS import fails for Linear WCS mode

### ISSUE THREAD

**Issue by MarkDurre** [veusz/veusz#231]
I can't import a FITS file under the default mode (Linear WCS) - other modes (Pixel Simple, Pixel WCS and Fractional) work fine. It gives me the error:
```
Traceback (most recent call last):
  File "veusz/dialogs/importdialog.py", line 277, in slotImport
  File "veusz/dataimport/dialog_fits.py", line 326, in doImport
  File "veusz/document/doc.py", line 170, in applyOperation
  File "veusz/dataimport/base.py", line 273, in do
  File "veusz/dataimport/defn_fits.py", line 363, in doImport
  File "veusz/dataimport/defn_fits.py", line 250, in readDataFromFile
  File "veusz/dataimport/defn_fits.py", line 215, in walkHdu
  File "veusz/dataimport/defn_fits.py", line 189, in readHduImage
  File "veusz/dataimport/defn_fits.py", line 172, in getImageWCS
TypeError: can't multiply sequence by non-int of type 'float'

Frame slotImport (File veusz/dialogs/importdialog.py, line 288)
 linked = False
 suffix = ''
 encoding = 'utf_8'
 filename = '/Users/mdurre/test.fits'
 tags = []
 importtab = <veusz.dataimport.dialog_fits.ImportTabFITS object at 0x10aa6a8b8>
 prefix = 'test.fits'
 self = <veusz.dialogs.importdialog.ImportDialog object at 0x10a7b35e8>
  self.Accepted = 1
  self.DrawChildren = 2
  self.DrawWindowBackground = 1
  self.IgnoreMask = 4
  self.PdmDepth = 6
  self.PdmDevicePixelRatio = 11
  self.PdmDevicePixelRatioScaled = 12
  self.PdmDpiX = 7
  self.PdmDpiY = 8
  self.PdmHeight = 2
  self.PdmHeightMM = 4
  self.PdmNumColors = 5
  self.PdmPhysicalDpiX = 9
  self.PdmPhysicalDpiY = 10
  self.PdmWidth = 1
  self.PdmWidthMM = 3
  self.Rejected = 0
  self.__dict__ = {'verticalLayout_4': <PyQt5.QtWidgets.QVBoxLayout object at 0x10a795b88>, 'hboxlayout': <PyQt5.QtWidgets.QHBoxLayout obj...
  self.__doc__ = 'Dialog box for importing data.\n    See ImportTab classes above which actually do the work of importing\n    '
  self.__module__ = 'veusz.dialogs.importdialog'
  self.browsebutton = <PyQt5.QtWidgets.QPushButton object at 0x10a795798>
  self.buttonBox = <PyQt5.QtWidgets.QDialogButtonBox object at 0x10a75c0d8>
  self.clipbutton = <PyQt5.QtWidgets.QToolButton object at 0x10a795678>
  self.dirname = '.'
  self.document = <veusz.document.doc.Document object at 0x10a690e58>
  self.encodingcombo = <veusz.qtwidgets.historyvaluecombo.HistoryValueCombo object at 0x10a75c828>
  self.filenamecompleter = <PyQt5.QtWidgets.QCompleter object at 0x10aa6aa68>
  self.filenameedit = <veusz.qtwidgets.historycombo.HistoryCombo object at 0x10a795708>
  self.filepreviewokay = True
  self.gridLayout_4 = <PyQt5.QtWidgets.QGridLayout object at 0x10a75c8b8>
  self.groupBox = <PyQt5.QtWidgets.QGroupBox object at 0x10a75c438>
  self.hboxlayout = <PyQt5.QtWidgets.QHBoxLayout object at 0x10a795d38>
  self.importbutton = <PyQt5.QtWidgets.QPushButton object at 0x10aa6a9d8>
  self.label = <PyQt5.QtWidgets.QLabel object at 0x10a7958b8>
  self.label_2 = <PyQt5.QtWidgets.QLabel object at 0x10a75cdc8>
  self.label_21 = <PyQt5.QtWidgets.QLabel object at 0x10a75c048>
  self.label_22 = <PyQt5.QtWidgets.QLabel object at 0x10a75c9d8>
  self.label_3 = <PyQt5.QtWidgets.QLabel object at 0x10a75c708>
  self.linkcheckbox = <veusz.qtwidgets.historycheck.HistoryCheck object at 0x10a75c798>
  self.mainwindow = <veusz.windows.mainwindow.MainWindow object at 0x10a690b88>
  self.methodtab = <PyQt5.QtWidgets.QTabWidget object at 0x10a74ee58>
  self.prefixcombo = <veusz.qtwidgets.historycombo.HistoryCombo object at 0x10a75c168>
  self.staticMetaObject = <PyQt5.QtCore.QMetaObject object at 0x10c47d6d8>
  self.suffixcombo = <veusz.qtwidgets.historycombo.HistoryCombo object at 0x10a75c948>
  self.tabs = {}
  self.tagcombo = <veusz.qtwidgets.historycombo.HistoryCombo object at 0x10a75cd38>
  self.verticalLayout_4 = <PyQt5.QtWidgets.QVBoxLayout object at 0x10a795b88>
  self.verticalLayout_6 = <PyQt5.QtWidgets.QVBoxLayout object at 0x10a75c5e8>

Frame doImport (File veusz/dataimport/dialog_fits.py, line 333)
 items = ['/primary']
 params = <veusz.dataimport.defn_fits.ImportParamsFITS object at 0x10c3d8c88>
 encoding = 'utf_8'
 slices = {}
 wcsmodes = {}
 node = <veusz.dataimport.fits_hdf5_tree.FileDataNode object at 0x10c3f0b00>
 tags = []
 namemap = {}
 suffix = ''
 recursiveitems = <function ImportTabFITS.doImport.<locals>.recursiveitems at 0x10c3dd488>
 doc = <veusz.document.doc.Document object at 0x10a690e58>
 linked = False
 filename = '/Users/mdurre/test.fits'
 op = <veusz.dataimport.defn_fits.OperationDataImportFITS object at 0x10c3d8cc0>
 prefix = 'test.fits'
 inname = ''
 twodranges = {}
 self = <veusz.dataimport.dialog_fits.ImportTabFITS object at 0x10aa6a8b8>
  self.DrawChildren = 2
  self.DrawWindowBackground = 1
  self.IgnoreMask = 4
  self.PdmDepth = 6
  self.PdmDevicePixelRatio = 11
  self.PdmDevicePixelRatioScaled = 12
  self.PdmDpiX = 7
  self.PdmDpiY = 8
  self.PdmHeight = 2
  self.PdmHeightMM = 4
  self.PdmNumColors = 5
  self.PdmPhysicalDpiX = 9
  self.PdmPhysicalDpiY = 10
  self.PdmWidth = 1
  self.PdmWidthMM = 3
  self.__dict__ = {'fitstwodgrp': <PyQt5.QtWidgets.QGroupBox object at 0x10aa6ae58>, 'oldselection': (<veusz.dataimport.fits_hdf5_tree.Fil...
  self.__doc__ = 'Tab for importing FITS file.'
  self.__module__ = 'veusz.dataimport.dialog_fits'
  self.datanodes = [<veusz.dataimport.fits_hdf5_tree.FileDataNode object at 0x10c3f0b00>]
  self.dialog = <veusz.dialogs.importdialog.ImportDialog object at 0x10a7b35e8>
  self.filefilter = 'FITS files'
  self.filetypes = ('.fits', '.fit', '.FITS', '.FIT')
  self.fitsimportstatus = <PyQt5.QtWidgets.QLabel object at 0x10aa6aca8>
  self.fitstreeview = <PyQt5.QtWidgets.QTreeView object at 0x10aa6adc8>
  self.fitstwodgrp = <PyQt5.QtWidgets.QGroupBox object at 0x10aa6ae58>
  self.fitstwodimport1d = <PyQt5.QtWidgets.QCheckBox object at 0x10aa6af78>
  self.fitstwodmaxx = <PyQt5.QtWidgets.QLineEdit object at 0x10cb864c8>
  self.fitstwodmaxy = <PyQt5.QtWidgets.QLineEdit object at 0x10cb86798>
  self.fitstwodminx = <PyQt5.QtWidgets.QLineEdit object at 0x10cb863a8>
  self.fitstwodminy = <PyQt5.QtWidgets.QLineEdit object at 0x10cb86678>
  self.fitswcsmode = <PyQt5.QtWidgets.QComboBox object at 0x10cb86168>
  self.gridLayout = <PyQt5.QtWidgets.QGridLayout object at 0x10aa6aee8>
  self.horizontalLayout = <PyQt5.QtWidgets.QHBoxLayout object at 0x10cb861f8>
  self.horizontalLayout_2 = <PyQt5.QtWidgets.QHBoxLayout object at 0x10cb86048>
  self.horizontalLayout_3 = <PyQt5.QtWidgets.QHBoxLayout object at 0x10cb86558>
  self.label = <PyQt5.QtWidgets.QLabel object at 0x10cb86288>
  self.label_2 = <PyQt5.QtWidgets.QLabel object at 0x10cb86318>
  self.label_3 = <PyQt5.QtWidgets.QLabel object at 0x10cb86438>
  self.label_4 = <PyQt5.QtWidgets.QLabel object at 0x10cb865e8>
  self.label_5 = <PyQt5.QtWidgets.QLabel object at 0x10cb86708>
  self.label_6 = <PyQt5.QtWidgets.QLabel object at 0x10cb860d8>
  self.oldselection = (<veusz.dataimport.fits_hdf5_tree.FileDataNode object at 0x10c3f0b00>, 'twod')
  self.resource = 'import_fits.ui'
  self.rootnode = <veusz.dataimport.fits_hdf5_tree.FileGroupNode object at 0x10cb877b8>
  self.staticMetaObject = <PyQt5.QtCore.QMetaObject object at 0x10c47de48>
  self.uiloaded = True
  self.verticalLayout = <PyQt5.QtWidgets.QVBoxLayout object at 0x10aa6ad38>
 twod_as_oned = set()

Frame applyOperation (File veusz/document/doc.py, line 171)
 operation = <veusz.dataimport.defn_fits.OperationDataImportFITS object at 0x10c3d8cc0>
 self = <veusz.document.doc.Document object at 0x10a690e58>
  self.__dict__ = {'historyredo': [], 'changeset': 0, 'modified': False, 'suspendupdates': [], 'evaluate': <veusz.document.evaluate.Evalua...
  self.__doc__ = 'Document class for holding the graph data.\n    '
  self.__module__ = 'veusz.document.doc'
  self.__weakref__ = None
  self.basewidget = <veusz.widgets.root.Root object at 0x10a71fdd8>
  self.changeset = 0
  self.data = {}
  self.datasettags = defaultdict(<class 'list'>, {})
  self.evaluate = <veusz.document.evaluate.Evaluate object at 0x10a71dcf8>
  self.filename = ''
  self.historybatch = []
  self.historyredo = []
  self.historyundo = [<veusz.document.operations.OperationLoadStyleSheet object at 0x10a7efdd8>, <veusz.document.operations.OperationLoadCust...
  self.locale = <PyQt5.QtCore.QLocale object at 0x10a730e48>
  self.modified = False
  self.pluginsloaded = True
  self.staticMetaObject = <PyQt5.QtCore.QMetaObject object at 0x10c47df98>
  self.suspendupdates = []

Frame do (File veusz/dataimport/base.py, line 273)
 document = <veusz.document.doc.Document object at 0x10a690e58>
 self = <veusz.dataimport.defn_fits.OperationDataImportFITS object at 0x10c3d8cc0>
  self.__dict__ = {'outinvalids': {}, 'outcustoms': [], 'params': <veusz.dataimport.defn_fits.ImportParamsFITS object at 0x10c3d8c88>, 'ou...
  self.__doc__ = 'Import 1d, 2d, text or nd data from a fits file.'
  self.__module__ = 'veusz.dataimport.defn_fits'
  self.__weakref__ = None
  self.descr = 'import FITS file'
  self.oldcustoms = None
  self.outcustoms = []
  self.outdatasets = {}
  self.outinvalids = {}
  self.outnames = []
  self.params = <veusz.dataimport.defn_fits.ImportParamsFITS object at 0x10c3d8c88>

Frame doImport (File veusz/dataimport/defn_fits.py, line 363)
 par = <veusz.dataimport.defn_fits.ImportParamsFITS object at 0x10c3d8c88>
 self = <veusz.dataimport.defn_fits.OperationDataImportFITS object at 0x10c3d8cc0>

Frame readDataFromFile (File veusz/dataimport/defn_fits.py, line 257)
 self = <veusz.dataimport.defn_fits.OperationDataImportFITS object at 0x10c3d8cc0>
 fitsf = [<pyfits.hdu.image.PrimaryHDU object at 0x10c40fcf8>]
 idx = 0
 item = '/primary'
 parts = ['primary']
 dsread = {}
 hdu = <pyfits.hdu.image.PrimaryHDU object at 0x10c40fcf8>
 hdunames = ['primary']

Frame walkHdu (File veusz/dataimport/defn_fits.py, line 215)
 self = <veusz.dataimport.defn_fits.OperationDataImportFITS object at 0x10c3d8cc0>
 dsread = {}
 hdu = <pyfits.hdu.image.PrimaryHDU object at 0x10c40fcf8>
 dsname = '/primary'

Frame readHduImage (File veusz/dataimport/defn_fits.py, line 189)
 attr = {}
 self = <veusz.dataimport.defn_fits.OperationDataImportFITS object at 0x10c3d8cc0>
 colattr = {}
 dsread = {}
 hdu = <pyfits.hdu.image.PrimaryHDU object at 0x10c40fcf8>
 dsname = '/primary'

Frame getImageWCS (File veusz/dataimport/defn_fits.py, line 172)
 attr = {}
 hdu = <pyfits.hdu.image.PrimaryHDU object at 0x10c40fcf8>
 wcs = [88.0475158691406, 22, '=-9.72222005657386e-06', -7.45617485046387, 32, 9.72222005657386e-06]
 mode = 'linear_wcs'
 dsname = '/primary'
 self = <veusz.dataimport.defn_fits.OperationDataImportFITS object at 0x10c3d8cc0>



```
[test.fits.zip](https://github.com/veusz/veusz/files/1715081/test.fits.zip)

**Comment by jeremysanders** [comment]
I think there's an issue with the fits file:

WARNING: The following header keyword is invalid or follows an unrecognized non-standard convention:
CDELT1  =-9.72222005657386e-06                                                   [astropy.io.fits.card]
WARNING: The following header keyword is invalid or follows an unrecognized non-standard convention:
CD1_1   =-9.72222005657386e-06                                                   [astropy.io.fits.card]

**Comment by MarkDurre** [comment]
Yep, that’s it.

Cheers,

Dr. Mark Durré
Centre for Astrophysics and Supercomputing
Swinburne University of Technology
PO Box 218, Hawthorn
Victoria 3122, Australia
Email: mdurre@swin.edu.au<mailto:mdurre@swin.edu.au>
