### ISSUE TITLE
Setting has no child axis3d 3D example does not open

### ISSUE THREAD

**Issue by jbaltrus** [veusz/veusz#261]
The awesome 3D version does not work when I open the first example using 3.0:

Setting has no child axis3d
Traceback (most recent call last):
  File "veusz\document\doc.py", line 570, in resolvePath
  File "veusz\setting\settings.py", line 181, in get
KeyError: 'axis3d'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "veusz\document\loader.py", line 157, in executeScript
  File "C:\Users\job314\AppData\Local\Temp\3d_example-1.vsz", line 3015, in <module>
    Set('StyleSheet/axis3d/autoRange', u'+2%')
  File "veusz\document\commandinterface.py", line 411, in Set
  File "veusz\document\doc.py", line 595, in resolveSettingPath
  File "veusz\document\doc.py", line 572, in resolvePath
ValueError: Settings has no child axis3d

**Comment by jeremysanders** [comment]
Thanks for the report. Are you sure that you're really using the latest version of Veusz, 3.0? This error only seems likely if there is an older version of Veusz installed on the system which is being picked up instead. If there is an older version, the version number being displayed is not necessarily the version of Veusz which is running. Old versions of veusz ahead in the Python path will be picked up first.

**Comment by jbaltrus** [comment]
It is 3.0. I open it first, check it the from Help and try and open the example 3d_surface, for example:

Traceback (most recent call last):
  File "veusz\document\loader.py", line 157, in executeScript
  File "C:\Program Files (x86)\Veusz\examples\3d_surface.vsz", line 10, in <module>
    Add('scene3d', name=u'scene3d1', autoadd=False)
  File "veusz\document\commandinterface.py", line 165, in Add
  File "veusz\document\doc.py", line 172, in applyOperation
  File "veusz\document\operations.py", line 414, in do
  File "veusz\document\widgetfactory.py", line 44, in makeWidget
KeyError: 'scene3d'

**Comment by jbaltrus** [comment]
Doesn't installer first uninstall the old version? It did for me before installing 3.0

**Comment by jeremysanders** [comment]
You didn't say which version you were using - windows binary, source code, mac...

It should delete the old one. Can you uninstall, check whether the C:\Program Files (x86)\Veusz is empty, then reinstall?

**Comment by jbaltrus** [comment]
Windows binary. Uninstalled, there was still PyQt5 folder there, deleted manually, reinstalled, working now. Thank you, please close

**Comment by jeremysanders** [comment]
Great - not sure what happened there. Maybe an old uninstaller that was missing some files.
