### ISSUE TITLE
crash on hdf5 file preview --> NameError: name 'ds' is not defined

### ISSUE THREAD

**Issue by greyltc** [veusz/veusz#269]
```
Veusz version: 3.0.1
Python version: 3.6.6 (default, Jun 27 2018, 13:11:40) 
[GCC 8.1.1 20180531]
Python platform: linux
Numpy version: 1.14.5
Qt version: 5.11.1
PyQt version: 5.11.2
SIP version: 4.19.12
Date: Sun, 29 Jul 2018 20:52:03 +0000

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/veusz/dialogs/importdialog.py", line 229, in slotUpdatePreview
    filename, encoding)
  File "/usr/lib/python3.6/site-packages/veusz/dataimport/dialog_hdf5.py", line 189, in doPreview
    self.rootnode, self.datanodes = constructTree(f)
  File "/usr/lib/python3.6/site-packages/veusz/dataimport/dialog_hdf5.py", line 135, in constructTree
    addsub(root, hdf5file, datanodes)
  File "/usr/lib/python3.6/site-packages/veusz/dataimport/dialog_hdf5.py", line 85, in addsub
    addsub(childnode, hchild, datanodes)
  File "/usr/lib/python3.6/site-packages/veusz/dataimport/dialog_hdf5.py", line 85, in addsub
    addsub(childnode, hchild, datanodes)
  File "/usr/lib/python3.6/site-packages/veusz/dataimport/dialog_hdf5.py", line 102, in addsub
    fdatatype = computedatatype(fdtype)
  File "/usr/lib/python3.6/site-packages/veusz/dataimport/dialog_hdf5.py", line 54, in computedatatype
    typ = h5py.check_dtype(vlen=ds.dtype)
NameError: name 'ds' is not defined
```

Fullerror report attached: [error.txt](https://github.com/veusz/veusz/files/2239174/error.txt)

**Comment by greyltc** [comment]
Offending data file attached: [Run19.zip](https://github.com/veusz/veusz/files/2239176/Run19.zip)

**Comment by jeremysanders** [comment]
Thanks for the report. I think the patch fixes the problem and will be in the next release.

**Comment by greyltc** [comment]
@jeremysanders have you tested your patch with the file I attached here?

**Comment by jeremysanders** [comment]
I think I did.

**Comment by greyltc** [comment]
That file has a compound dataset in it with column 0 being integers and column 1 being variable length strings. I'm just curious if that imports correctly.

**Comment by jeremysanders** [comment]
It seemed to import the variable length strings ok, if I remember correctly.
