### ISSUE TITLE
Veusz fails to lauch: PyCapsule_GetPointer called with incorrect name

### ISSUE THREAD

**Issue by badshah400** [veusz/veusz#286]
Veusz fails to launch with recent sip (4.19.12+) and PyQt5, probably because it doesn't use the required copies of the now private sip python modules:

```
:~> veusz
Traceback (most recent call last):
  File "/usr/bin/veusz", line 11, in <module>
    load_entry_point('veusz==3.0.1', 'gui_scripts', 'veusz')()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 484, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2725, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2343, in load
    return self.resolve()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2349, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib64/python3.6/site-packages/veusz/veusz_main.py", line 31, in <module>
    from veusz import utils
  File "/usr/lib64/python3.6/site-packages/veusz/utils/__init__.py", line 22, in <module>
    from .textrender import Renderer, FontMetrics, latexEscape
  File "/usr/lib64/python3.6/site-packages/veusz/utils/textrender.py", line 30, in <module>
    from . import points
  File "/usr/lib64/python3.6/site-packages/veusz/utils/points.py", line 25, in <module>
    from ..helpers.qtloops import plotPathsToPainter
ValueError: PyCapsule_GetPointer called with incorrect name
```

Other apps have seen similar problems, see:
* https://issues.qgis.org/issues/19476
* Ultimaker/libArcus#76

**Comment by jeremysanders** [comment]
I assume this ok now? Please reopen if a problem. Veusz supports SIP5 now, so maybe things have changed.

**Comment by badshah400** [comment]
Yes, this has been fixed for a while. Thanks.
