### ISSUE TITLE
veusz 3.0.1 gnu/linux (Import Error Qt_5.9 not found)

### ISSUE THREAD

**Issue by andres-GHub** [veusz/veusz#292]

**Comment by andres-GHub** [comment]
hi, I'm having some issues running veusz 3.0.1 on  32-bit lubuntu 16.04. After following the INSTALL instructions and running 'veusz' I get the following:

Traceback (most recent call last):
  File "/usr/local/bin/veusz", line 23, in <module>
    import veusz.veusz_main
  File "/usr/local/lib/python2.7/dist-packages/veusz/veusz_main.py", line 32, in <module>
    from veusz import utils
  File "/usr/local/lib/python2.7/dist-packages/veusz/utils/__init__.py", line 22, in <module>
    from .textrender import Renderer, FontMetrics, latexEscape
  File "/usr/local/lib/python2.7/dist-packages/veusz/utils/textrender.py", line 30, in <module>
    from . import points
  File "/usr/local/lib/python2.7/dist-packages/veusz/utils/points.py", line 25, in <module>
    from ..helpers.qtloops import plotPathsToPainter
ImportError: /usr/lib/i386-linux-gnu/sse2/libQt5Core.so.5: version `Qt_5.9' not found (required by /usr/local/lib/python2.7/dist-packages/veusz/helpers/qtloops.so)
 
-----------------
I've re-installed Qt5 (and the stipulated required programs) both through anaconda and directly in the terminal through apt-get, but haven't been able to get it to work. I noticed that even though I installed Qt5 in anaconda it was not until I used 'apt-get' that the installed veusz was able to recognise that qt5 was installed.
cheers

**Comment by jeremysanders** [comment]
It looks like it's built against the wrong Qt version. Make sure you're running setup.py with the same python version you're running veusz with.

**Comment by jeremysanders** [comment]
It might depend on which qmake setup finds on your path - it uses this by default to choose which qt to link to.
