### ISSUE TITLE
Ubuntu ppa installation issue

### ISSUE THREAD

**Issue by SergeyRa** [veusz/veusz#389]
After adding jeremysanders/ppa and executing 'sudo apt-get install veusz' in Ubuntu 18.04.4 LTS, the main menu shortcut does not launch the program (probably due to incorrect path in veusz.desktop file).

**Comment by jeremysanders** [comment]
Does it work if run from the command line? I can't see a problem on Ubuntu 19.10, using the same build source. In the veusz.desktop it should just say

    Exec=veusz %F

Does yours say the same thing? One possible problem is if you have another version on the computer installed a different way.

**Comment by SergeyRa** [comment]
The 'Exec' item in .desktop file is exactly 'veusz %F'. Launching of 'veusz' command from terminal results in:

Traceback (most recent call last):
  File "/usr/bin/veusz", line 11, in <module>
    load_entry_point('veusz==3.2', 'gui_scripts', 'veusz')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/veusz/veusz_main.py", line 32, in <module>
    from veusz import utils
  File "/usr/lib/python3/dist-packages/veusz/utils/__init__.py", line 22, in <module>
    from .textrender import Renderer, FontMetrics, latexEscape
  File "/usr/lib/python3/dist-packages/veusz/utils/textrender.py", line 30, in <module>
    from . import points
  File "/usr/lib/python3/dist-packages/veusz/utils/points.py", line 25, in <module>
    from ..helpers.qtloops import plotPathsToPainter
ValueError: PyCapsule_GetPointer called with incorrect name

**Comment by jeremysanders** [comment]
Thanks for that information. That error sounds like you may have another Veusz copy on your system which is interfering with the current ppa version. I changed the way the helpers was packaged in the distribution, so it's possible you have a broken helper package which didn't get uninstalled.

Perhaps you could try `apt remove "*veusz*"` (or purge) to make sure there's no extra package, then reinstall the main veusz package.

If that doesn't work, would it be possible to to look for other qtloops versions on the system, e.g. doing `find / -name "*qtloops*so*"` ?

**Comment by SergeyRa** [comment]
I tried re-installation after complete removal of all veusz-related packages, and still have the same error. The qtloops search haven't found any results.
By the way, both the binary (downloaded directly from veusz main page) and old 1.2 version (installed by apt-get when your PPA is not added) work well.

**Comment by sphh** [comment]
I have the same problem. I read #286 and #336 

```shell
$ sudo find / -name "*sip*so*"
/usr/lib/python3/dist-packages/sip.cpython-38-x86_64-linux-gnu.so
/usr/local/lib/python3.8/dist-packages/PyQt5/sip.cpython-38-x86_64-linux-gnu.so
```

The local version was installed when I installed `Spyder` with the help of `pip3` and I don't want to uninstall `Spyder`.

Is there a way to start `veusz` successfully?

My system:
Linux Mint 20, veusz installed via ppa.

Workaround:
I downloaded the binary distribution and this seems to work.

**Comment by jeremysanders** [comment]
You probably should put your local sip into a virtualenv so it's no picked up by the default python command.

**Comment by sphh** [comment]
What is actually the underlying problem? Different version of `sip.cpython*.so`?

**Comment by jeremysanders** [comment]
The sip API changes with new releases.  You need the same version of sip.cpython*.so as the sip that veusz was compiled using.
