### ISSUE TITLE
Exporting graphics into Vector formats changes the plots

### ISSUE THREAD

**Issue by drich-colorman** [veusz/veusz#407]
I have just created a plot for a publication.  The wanted it in a vector format such as SVG or EMF.  When I tried to export the graph as SVG, the markers on the curves were stripped stripped.  When I tried to export as EMF the image 5000 x 5000 pixels and when it opened it was a zoomed in image of the axis labels and markers.
[Veusz_Graphs.zip](https://github.com/veusz/veusz/files/4646976/Veusz_Graphs.zip)

**Comment by jeremysanders** [comment]
Hi - you didn't attach the CSV file necessary to open the document. Your SVG file looks fine to me, either loaded in Inkscape, Firefox or MS Edge. Your EMF file looks fine to me inserted in LibreOffice or Microsoft Word. How are you seeing problems?

**Comment by drich-colorman** [comment]
I am new to Veusz so I assumed that the csv data were stored inside of the VSZ file, once the import had been executed.

When I load the SVG file into Edge it opens at 800X and will not zoom down.   I do not use Edge much.  When I opened in Internet Explorer it is missing the markers.  So, I tried Chrome and it previews just fine in Chrome.  The EMF is another story.  Paint is supposed to be able to open this format but on my version of Windows 10 it says that it does not recognize the EMF as a valid file.  PaintShopPro is supposed to be able to open EMF but it cannot figure out the format of the exported graphic.

So I am now willing to believe that it is my viewing tools that cannot properly preview the file before I send it off to the editors.

Danny C. Rich, PhD
Senior Color Physicist
Sun Chemical Corporation
Color Research Laboratory
631 Central Avenue
Carlstadt, NJ, 07072, USA
O: +1 201 933 4500  x1144
M: +1 973 580 4326
Web: www.sunchemical.com<http://www.sunchemical.com/>
Email: danny.rich@sunchemical.com<mailto:danny.rich@sunchemical.com>

working for you.

**Comment by And0k** [comment]
Vectors (their ends) disappear when exporting to SVG if vectors have arrows of types that are not filled, and if, in same time, Hide property of vector's Line is True. For other formats they do not disappear <details><summary>(cannot check for EMF because of exporting error)</summary>
Veusz 3.6.2, Windows 11
```
Traceback (most recent call last):
  File "veusz\document\export.py", line 74, in run
  File "veusz\document\export.py", line 325, in doExport
  File "veusz\document\emf_export.py", line 192, in saveFile
  File "pyemf3\emf.py", line 214, in save
  File "pyemf3\emf.py", line 225, in _serialize
  File "pyemf3\emr.py", line 75, in serialize
  File "pyemf3\field.py", line 408, in pack
  File "pyemf3\field.py", line 115, in pack
struct.error: argument out of range

Frame run (File veusz\document\export.py, line 75)
 self = <veusz.document.export.ExportEMFRunnable object at 0x0000020636E7A5F0>
  self.__dict__ = {'aexport': <veusz.document.export.AsyncExport object at 0x0000020636E7A680>, 'filename': 'B:\\WorkData\\Cruises(older)\...
  self.__doc__ = 'Runnable task to export EMF output.'
  self.__module__ = 'veusz.document.export'
  self.__weakref__ = None
  self.aexport = <veusz.document.export.AsyncExport object at 0x0000020636E7A680>
  self.filename = 'Vprogress_7441A@ADCP#...
  self.phelpers = [<veusz.document.painthelper.PaintHelper object at 0x000002063CAEED40>]

Frame doExport (File veusz\document\export.py, line 325)
 self = <veusz.document.export.ExportEMFRunnable object at 0x0000020636E7A5F0>
 dpi = (90, 90)
 size = (662.5984251968504, 588.1889763779528)
 paintdev = <veusz.document.emf_export.EMFPaintDevice object at 0x000002063458E500>

Frame saveFile (File veusz\document\emf_export.py, line 192)
 self = <veusz.document.emf_export.EMFPaintEngine object at 0x000002063458F220>
  self.AllDirty = 65535
  self.AllFeatures = -1
  self.AlphaBlend = 128
  self.Antialiasing = 1024
  self.BlendModes = 32768
  self.Blitter = 16
  self.BrushStroke = 2048
  self.ConicalGradientFill = 64
  self.ConstantOpacity = 4096
  self.ConvexMode = 2
  self.CoreGraphics = 3
  self.Direct2D = 17
  self.Direct3D = 11
  self.DirtyBackground = 16
  self.DirtyBackgroundMode = 32
  self.DirtyBrush = 2
  self.DirtyBrushOrigin = 4
  self.DirtyClipEnabled = 2048
  self.DirtyClipPath = 256
  self.DirtyClipRegion = 128
  self.DirtyCompositionMode = 1024
  self.DirtyFont = 8
  self.DirtyHints = 512
  self.DirtyOpacity = 4096
  self.DirtyPen = 1
  self.DirtyTransform = 64
  self.LinearGradientFill = 16
  self.MacPrinter = 4
  self.MaskedBrush = 8192
  self.MaxUser = 100
  self.ObjectBoundingModeGradients = 65536
  self.OddEvenMode = 0
  self.OpenGL = 7
  self.OpenGL2 = 14
  self.OpenVG = 13
  self.PaintBuffer = 15
  self.PaintOutsidePaintEvent = 536870912
  self.PainterPaths = 512
  self.PatternBrush = 8
  self.PatternTransform = 2
  self.Pdf = 12
  self.PerspectiveTransform = 16384
  self.Picture = 8
  self.PixmapTransform = 4
  self.PolylineMode = 3
  self.PorterDuff = 256
  self.PostScript = 6
  self.PrimitiveTransform = 1
  self.QWindowSystem = 5
  self.QuickDraw = 2
  self.RadialGradientFill = 32
  self.Raster = 10
  self.RasterOpModes = 131072
  self.SVG = 9
  self.User = 50
  self.WindingMode = 1
  self.Windows = 1
  self.X11 = 0
  self.__dict__ = {'width': 7.362204724409448, 'height': 6.535433070866143, 'dpi': 90, 'emf': <pyemf3.emf.EMF object at 0x000002063CAEF4F0...
  self.__doc__ = 'Custom EMF paint engine.'
  self.__module__ = 'veusz.document.emf_export'
  self.__weakref__ = None
  self.brush = 2147483653
  self.dpi = 90
  self.emf = <pyemf3.emf.EMF object at 0x000002063CAEF4F0>
  self.height = 6.535433070866143
  self.paintdevice = <veusz.document.emf_export.EMFPaintDevice object at 0x000002063458E500>
  self.pen = 3
  self.pencolor = (0, 0, 0)
  self.width = 7.362204724409448
 filename = 'Vprogress_7441A@ADCP#...

Frame save (File pyemf3\emf.py, line 218)
 self = <pyemf3.emf.EMF object at 0x000002063CAEF4F0>
  self.__dict__ = {'filename': 'Vprogres...
  self.__doc__ = '\nReference page of the public API for enhanced metafile creation.  See\nL{pyemf} for an overview / mini tutorial.\n\n@...
  self.__module__ = 'pyemf3.emf'
  self.__weakref__ = None
  self.dc = <pyemf3.dc.DC object at 0x000002063CAEECE0>
  self.filename = 'Vprogress_7441A@ADCP#...
  self.pathstart = 3113
  self.records = [<pyemf3.emr.HEADER object at 0x000002063CAEF3A0>, <pyemf3.emr.BEGINPATH object at 0x000002063CAEED70>, <pyemf3.emr.MOVE...
  self.scaleheader = True
  self.verbose = False
 filename = 'Vprogress_7441A@ADCP#...
 fh = <_io.BufferedWriter name='7441A#D80...

Frame _serialize (File pyemf3\emf.py, line 225)
 self = <pyemf3.emf.EMF object at 0x000002063CAEF4F0>
 fh = <_io.BufferedWriter name='7441A#D80...
 e = <pyemf3.emr.MOVETOEX object at 0x000002063D6902E0>

Frame serialize (File pyemf3\emr.py, line 80)
 self = <pyemf3.emr.MOVETOEX object at 0x000002063D6902E0>
  self.__dict__ = {'values': {'ptl_x': -3355442887, 'ptl_y': 18043}, 'nSize': 16, 'iType': 27, 'verbose': False, 'datasize': 0, 'data': No...
  self.__doc__ = None
  self.__module__ = 'pyemf3.emr'
  self.__weakref__ = None
  self.data = None
  self.datasize = 0
  self.emr_id = 27
  self.error = 0
  self.format = <pyemf3.field.RecordFormat object at 0x00000206345AC820>
  self.iType = 27
  self.nSize = 16
  self.twobytepadding = b'\x00\x00'
  self.typedef = [('i', 'ptl_x'), ('i', 'ptl_y')]
  self.unhandleddata = None
  self.values = {'ptl_x': -3355442887, 'ptl_y': 18043}
  self.verbose = False
 fh = <_io.BufferedWriter name='7441A#D80...

Frame pack (File pyemf3\field.py, line 412)
 self = <pyemf3.field.RecordFormat object at 0x00000206345AC820>
  self.__dict__ = {'typedef': [('i', 'ptl_x'), ('i', 'ptl_y')], 'minstructsize': 8, 'endian': '<', 'fmtmap': {'ptl_x': <pyemf3.field.Struc...
  self.__doc__ = None
  self.__module__ = 'pyemf3.field'
  self.__weakref__ = None
  self.debug = 0
  self.default = {'ptl_x': None, 'ptl_y': None}
  self.default_endian = '<'
  self.endian = '<'
  self.fmt = '<i<i'
  self.fmtmap = {'ptl_x': <pyemf3.field.StructFormat object at 0x00000206345AF0A0>, 'ptl_y': <pyemf3.field.StructFormat object at 0x0000...
  self.minstructsize = 8
  self.names = ['ptl_x', 'ptl_y']
  self.typedef = [('i', 'ptl_x'), ('i', 'ptl_y')]
 values = {'ptl_x': -3355442887, 'ptl_y': 18043}
 obj = <pyemf3.emr.MOVETOEX object at 0x000002063D6902E0>
 alreadypacked = 8
 fh = <_io.BytesIO object at 0x0000020636ED67F0>
 size = 0
 output = {}
 name = 'ptl_x'
 fmt = <pyemf3.field.StructFormat object at 0x00000206345AF0A0>

Frame pack (File pyemf3\field.py, line 115)
 self = <pyemf3.field.StructFormat object at 0x00000206345AF0A0>
  self.__dict__ = {'fmt': '<i', 'size': 4, 'num': 1, 'offset': None, 'debug': False}
  self.__doc__ = None
  self.__module__ = 'pyemf3.field'
  self.__weakref__ = None
  self.debug = False
  self.fmt = '<i'
  self.num = 1
  self.offset = None
  self.size = 4
 obj = <pyemf3.emr.MOVETOEX object at 0x000002063D6902E0>
 name = 'ptl_x'
 value = -3355442887
```
</details>
