### ISSUE TITLE
Can't fit graph to an exponential function

### ISSUE THREAD

**Issue by bhanudaysharma** [veusz/veusz#408]
I was trying to fit a function to an exponential function (y= a*exp(b*x)) or (y= a* 2.71828**(b*x)), but got following error:
```
Fit results:
    a = nan ± nan (+nan / nan)
    b = nan ± nan (+nan / nan)
chi^2 = nan, dof = 2498, reduced-chi^2 = nan
Traceback (most recent call last):
  File "veusz\windows\consolewindow.py", line 258, in runFunction
  File "veusz\widgets\fit.py", line 376, in actionFit
  File "veusz\document\doc.py", line 182, in applyOperation
  File "veusz\document\operations.py", line 1149, in do
  File "veusz\document\operations.py", line 83, in do
  File "veusz\setting\setting.py", line 131, in set
  File "veusz\setting\setting.py", line 491, in normalize
  File "veusz\setting\setting.py", line 457, in _finiteRangeFloat
veusz.utils.utilfuncs.InvalidType: Finite values only allowed

```

**Comment by jeremysanders** [comment]
Maybe your initial parameters are strange, or one of your points has a zero-sized error bar?

**Comment by bhanudaysharma** [comment]
> Maybe your initial parameters are strange, or one of your points has a zero-sized error bar?

Thanks @jeremysanders . I was able to get the fit by altering initial parameters. First I tried some other initial guesses, but it didn't work. Then I fit the data to a straight line (y=a*x+b) and then used those values of 'a' and 'b' to fit the exponential curve (y = a*exp(b*x)).  Somehow it worked. 

Thanks for such a great software.
