### ISSUE TITLE
./run_veusz_inplace hangs

### ISSUE THREAD

**Issue by sphh** [veusz/veusz#482]
I downloaded and compiled veusz 3.3.1 successfully on a Linux system. I executed the command `cp build/*/veusz/helpers/*.so veusz/helpers/` and when I run `./run_veusz_inplace` I get this error:
```python3
VO table import: astropy module not available
Traceback (most recent call last):
  File "/home/sph/Software/bin/veusz-3.3.1/veusz/veusz_main.py", line 146, in run
    from veusz import widgets
  File "/home/sph/Software/bin/veusz-3.3.1/veusz/widgets/__init__.py", line 50, in <module>
    from .scene3d import Scene3D
  File "/home/sph/Software/bin/veusz-3.3.1/veusz/widgets/scene3d.py", line 31, in <module>
    from ..helpers import threed
ImportError: dynamic module does not define module export function (PyInit_threed)
Traceback (most recent call last):
  File "/home/sph/Software/bin/veusz-3.3.1/veusz/veusz_main.py", line 279, in slotStartApplication
    from veusz.utils import vzdbus, vzsamp
  File "/home/sph/Software/bin/veusz-3.3.1/veusz/utils/vzsamp.py", line 21, in <module>
    from ..windows.mainwindow import MainWindow
  File "/home/sph/Software/bin/veusz-3.3.1/veusz/windows/mainwindow.py", line 46, in <module>
    from . import plotwindow
  File "/home/sph/Software/bin/veusz-3.3.1/veusz/windows/plotwindow.py", line 34, in <module>
    from .. import widgets
  File "/home/sph/Software/bin/veusz-3.3.1/veusz/widgets/__init__.py", line 50, in <module>
    from .scene3d import Scene3D
  File "/home/sph/Software/bin/veusz-3.3.1/veusz/widgets/scene3d.py", line 31, in <module>
    from ..helpers import threed
ImportError: dynamic module does not define module export function (PyInit_threed)
```
Nothing happens now and I cannot even stop veusz with `CTRL-C`. I have to kill it with `kill <pid>`.

What is the reason? How do I resolve it?

**Comment by jeremysanders** [comment]
Are you sure you didn't compile with python2, and run with python3 (e.g. https://github.com/orocos/orocos_kinematics_dynamics/issues/96)?

`./run_veusz_inplace` uses python3 by default I think. You could trying doing `python ./run_veusz_inplace` to force a python2 run, or recompile with python3.

**Comment by sphh** [comment]
I compiled with
```sh
python3 setup.py build
```

I looked through the output of the compiling process and all mentions of `python` are either `python3`, `python3.8` or `cpython-38` …

**Comment by sphh** [comment]
I tried to run
```sh
$ python2 ./run_veusz_inplace
Traceback (most recent call last):
  File "./run_veusz_inplace", line 37, in <module>
    import veusz.veusz_main
  File "/home/sph/Software/bin/veusz-3.3.1/veusz/veusz_main.py", line 31, in <module>
    from veusz import qtall as qt
  File "/home/sph/Software/bin/veusz-3.3.1/veusz/qtall.py", line 23, in <module>
    from PyQt5.QtCore import *
ImportError: No module named PyQt5.QtCore
```

If I specify the python version like this:
```sh
$ python3.8 ./run_veusz_inplace
```
I get the error mentioned in my original post.

**Comment by jeremysanders** [comment]
This is difficult to diagnose, but there's likely some problem in your build environment. You could try deleting the build directory and trying again (if you tried multiple times before and had some failures earlier).

You could try
```
python3 setup.py build_ext --inplace
```
Instead of building and copying (delete the `*.so` files in the `veusz/helpers/` directory first).

Otherwise, I read someone reporting that they had a different version of sip to the one installed. Could you have multiple versions of sip or PyQt5 (e.g. a distribution one and one downloaded via pip)?

**Comment by sphh** [comment]
Thanks for the hints. The compilation was a trial and error process until I had gathered all the packages needed. I run the compilation until an error told me, a package was missing. I installed that package and rerun the compilation.

Now with all the packages needed for the compilation in place I removed the whole source tree, uncompressed it again and did a fresh compilation and voilà, it works! Your note "You could try … trying again" was the important bit.

Thanks for your help!!

BTW veusz is such a great package!!

**Comment by jeremysanders** [comment]
Glad I could help!
