### ISSUE TITLE
range of plotting a fitted curve

### ISSUE THREAD

**Issue by bsmile001** [veusz/veusz#487]
I choose to fit a set of data within a given range but hope the fitted curve can be plotted throughout the whole data range. Can this be done? The default seems to only plot the fitted function within the fitted range.

**Comment by jeremysanders** [comment]
Probably only by fitting a subset of data, e.g. fit xdata[(xdata>2)&(xdata<6)] and ydata[(xdata>2)&(xdata<6)], or use the dataset filtering to make a subset of the data.

**Comment by bsmile001** [comment]
Do you mean I uncheck the "fit only range" option but supply the data range in xdata and ydata box? I tried it to add 

rntotr**3/4>25 && rntotr**3/4 < 30

into xdata box and clicked fit function, but it returns the following error

Error in expression 'rntotr**3/4>25 && rntotr**3/4 < 30': Unable to parse file: invalid syntax (<string>, line 1)
Traceback (most recent call last):
  File "veusz\windows\consolewindow.py", line 258, in runFunction
  File "veusz\widgets\fit.py", line 254, in actionFit
AttributeError: 'NoneType' object has no attribute 'data'

Thanks for further help,

**Comment by jeremysanders** [comment]
Either you create a new dataset in the Data->Filter dialog box and fit that new dataset, or enter an expression. Entering an expression removes error bars, however.

The expression has to be a numpy array expression, so you need something like `rntotr3[(rntotr3/4>25)&(rntotr3/4)]`. This selects elements from the array where the expression is True.

Note that `&&` doesn't work with arrays, hence the brackets and `&` (`logical_and(a,b)` is an alternative). For the filtering, you'd enter an expression like what is in the square brackets above.
