### ISSUE TITLE
iminuit fit crash on Fedora

### ISSUE THREAD

**Issue by cunio** [veusz/veusz#502]
When I try to fit in veusz I get this message:

```
Traceback (most recent call last):
  File "/usr/lib64/python3.9/site-packages/veusz/windows/consolewindow.py", line 258, in runFunction
    func()
  File "/usr/lib64/python3.9/site-packages/veusz/widgets/fit.py", line 341, in actionFit
    vals, chi2, dof = minuitFit(
  File "/usr/lib64/python3.9/site-packages/veusz/widgets/fit.py", line 99, in minuitFit
    print(_('Fit results:\n') + "\n".join([
  File "/usr/lib64/python3.9/site-packages/veusz/widgets/fit.py", line 101, in <listcomp>
    % (n, m.values[n], m.errors[n], m.merrors[(n, 1.0)],
  File "/home/user/.local/lib/python3.9/site-packages/iminuit/util.py", line 743, in __getitem__
    return OrderedDict.__getitem__(self, key)
KeyError: ('a', 1.0)

```
I have iminuit-2.3.0 installed via pip3 install iminuit

**Comment by cunio** [comment]
Downgrading to iminuit via 
`pip3 install iminuit==1.5.4`
helped.
It appears that Veusz fit in not compatible with iminuit >=2.0.0

**Comment by korintje** [comment]
@jeremysanders
Thanks for the review and merge!
I assume that we can close this issue now?

**Comment by jeremysanders** [comment]
Thanks - I forgot again
