### ISSUE TITLE
Trying to copy details of hatch-filling of bar graph across widgets causes a crash

### ISSUE THREAD

**Issue by Mrhnhrm** [veusz/veusz#525]
Hi there,

I was adjusting filling styles for a stacked bar graph. I decided that my hatch-filling of the bars needs thicker lines. I changed it in one fill style (one bar in a stack), and decided to "copy to all bar widgets", hoping that it will affect line thickness in the whole document. Veusz crashed down.

Maybe it would help to know that my graph had multiple bar graph widgets.

The crash report follows:

> Veusz version: 3.3.1
> Python version: 3.7.4 (default, Oct 16 2019, 09:38:57) 
> [GCC 8.3.1 20190311 (Red Hat 8.3.1-3)]
> Python platform: linux
> Numpy version: 1.17.2
> Qt version: 5.13.1
> PyQt version: 5.13.1
> SIP version: 4.19.19
> Date: Пт, 16 апр 2021 07:41:06 +0000
> 
> Traceback (most recent call last):
>   File "veusz/windows/treeeditwindow.py", line 1498, in actionCopyTypedWidgets
>   File "veusz/document/doc.py", line 185, in applyOperation
>   File "veusz/document/operations.py", line 145, in do
>   File "veusz/setting/settings.py", line 181, in get
> KeyError: 'tempbrush'
> 
> Frame actionCopyTypedWidgets (File veusz/windows/treeeditwindow.py, line 1498)
>  self = <veusz.windows.treeeditwindow.SettingLabel object at 0x7fad2099a5f0>
>   self.DrawChildren = 2
>   self.DrawWindowBackground = 1
>   self.IgnoreMask = 4
>   self.PdmDepth = 6
>   self.PdmDevicePixelRatio = 11
>   self.PdmDevicePixelRatioScaled = 12
>   self.PdmDpiX = 7
>   self.PdmDpiY = 8
>   self.PdmHeight = 2
>   self.PdmHeightMM = 4
>   self.PdmNumColors = 5
>   self.PdmPhysicalDpiX = 9
>   self.PdmPhysicalDpiY = 10
>   self.PdmWidth = 1
>   self.PdmWidthMM = 3
>   self.__dict__ = {'document': <veusz.document.doc.Document object at 0x7fad22b1aa50>, 'setting': <veusz.setting.setting.DistancePt object...
>   self.__doc__ = 'A label to describe a setting.\n\n    This widget shows the name, a tooltip description, and gives\n    access to the c...
>   self.__module__ = 'veusz.windows.treeeditwindow'
>   self._clickwidget = <veusz.widgets.bar.BarPlotter object at 0x7fad22b859d0>
>   self.document = <veusz.document.doc.Document object at 0x7fad22b1aa50>
>   self.iconlabel = <PyQt5.QtWidgets.QLabel object at 0x7fad2099a410>
>   self.infocus = True
>   self.inmenu = True
>   self.inmouse = False
>   self.labelicon = <PyQt5.QtWidgets.QLabel object at 0x7fad2099a4b0>
>   self.layout = <PyQt5.QtWidgets.QHBoxLayout object at 0x7fad2099a550>
>   self.setnsproxy = <veusz.setting.controls._FillBox.__init__.<locals>.DirectSetProxy object at 0x7fad20987410>
>   self.setting = <veusz.setting.setting.DistancePt object at 0x7fad20987590>
>   self.staticMetaObject = <PyQt5.QtCore.QMetaObject object at 0x7fad20963350>
> 
> Frame applyOperation (File veusz/document/doc.py, line 186)
>  self = <veusz.document.doc.Document object at 0x7fad22b1aa50>
>   self.__dict__ = {'changeset': 279, 'datasettags': defaultdict(<class 'list'>, {}), 'suspendupdates': [], 'locale': <PyQt5.QtCore.QLocale...
>   self.__doc__ = 'Document class for holding the graph data.\n    '
>   self.__module__ = 'veusz.document.doc'
>   self.__weakref__ = None
>   self.basewidget = <veusz.widgets.root.Root object at 0x7fad22b2a850>
>   self.changeset = 279
>   self.data = {'180 5-HMF': <veusz.datasets.oned.Dataset object at 0x7fad22b74b50>, '180 furfural': <veusz.datasets.oned.Dataset objec...
>   self.datasettags = defaultdict(<class 'list'>, {})
>   self.evaluate = <veusz.document.evaluate.Evaluate object at 0x7fad323bf350>
>   self.filename = '/home/mrhn/Documents/2021/03-paper-baryshnikov/figs/reuse.vsz'
>   self.historybatch = []
>   self.historyredo = []
>   self.historyundo = [<veusz.document.operations.OperationSettingSet object at 0x7fad22baa6d0>, <veusz.document.operations.OperationSettingSe...
>   self.locale = <PyQt5.QtCore.QLocale object at 0x7fad30448950>
>   self.modified = True
>   self.pluginsloaded = True
>   self.staticMetaObject = <PyQt5.QtCore.QMetaObject object at 0x7fad22c5b750>
>   self.suspendupdates = []
>  operation = <veusz.document.operations.OperationSettingPropagate object at 0x7fad209872d0>
>  redoing = False
> 
> Frame do (File veusz/document/operations.py, line 145)
>  self = <veusz.document.operations.OperationSettingPropagate object at 0x7fad209872d0>
>   self.__dict__ = {'val': '1pt', 'widgetname': None, 'rootpath': None, 'maxlevels': -1, 'setpath': ['BarFill', 'tempbrush', 'linewidth'], ...
>   self.__doc__ = 'Propagate setting to other widgets.'
>   self.__module__ = 'veusz.document.operations'
>   self.__weakref__ = None
>   self.descr = 'propagate setting'
>   self.maxlevels = -1
>   self.restorevals = {}
>   self.rootpath = None
>   self.setpath = ['BarFill', 'tempbrush', 'linewidth']
>   self.val = '1pt'
>   self.widgetname = None
>   self.widgettype = 'bar'
>  document = <veusz.document.doc.Document object at 0x7fad22b1aa50>
>  root = <veusz.widgets.root.Root object at 0x7fad22b2a850>
>  widgetlist = [<veusz.widgets.bar.BarPlotter object at 0x7fad22b716d0>, <veusz.widgets.bar.BarPlotter object at 0x7fad22b859d0>]
>  w = <veusz.widgets.bar.BarPlotter object at 0x7fad22b716d0>
>  s = <veusz.widgets.bar.BarFill object at 0x7fad22b71dd0>
>  i = 'tempbrush'
> 
> Frame get (File veusz/setting/settings.py, line 181)
>  self = <veusz.widgets.bar.BarFill object at 0x7fad22b71dd0>
>   self.__dict__ = {'setdict': {'fills': <veusz.setting.setting.FillSet object at 0x7fad22b71e50>}, 'name': 'BarFill', 'descr': 'Bar fill',...
>   self.__doc__ = 'Filling of bars.'
>   self.__module__ = 'veusz.widgets.bar'
>   self.__weakref__ = None
>   self.descr = 'Bar fill'
>   self.issetting = False
>   self.issettings = True
>   self.iswidget = False
>   self.name = 'BarFill'
>   self.nodetype = 'settings'
>   self.parent = <veusz.setting.settings.Settings object at 0x7fad22b71790>
>   self.pixmap = 'settings_bgfill'
>   self.setdict = {'fills': <veusz.setting.setting.FillSet object at 0x7fad22b71e50>}
>   self.setnames = ['fills']
>   self.setnsmode = 'formatting'
>   self.usertext = 'Fill'
>  name = 'tempbrush'
> 

Thanks for your attention.
-- Nico

**Comment by jeremysanders** [comment]
Strange. I tried to reproduce this but I can't see a problem. If you can reproduce this from a blank document please let me know.
