### ISSUE TITLE
veusz fails to start after installing on Ubuntu

### ISSUE THREAD

**Issue by deskoop** [veusz/veusz#534]
Linux (ubuntu) here.  I just installed veusz (using sudo apt install veusz). Installation completes without error. However when calling veusz I get the error below. Maybe it helps: I am suffering with pip-vs-anaconda hell, so maybe there is something wrong with my current setup. This being said, I would like to know if there is something obvious that I could check to make it work.

```
user@user-pc:~$ veusz
Traceback (most recent call last):
  File "/usr/bin/veusz", line 11, in <module>
    load_entry_point('veusz==3.3.1', 'gui_scripts', 'veusz')()
  File "/home/user/.local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 474, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/user/.local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2846, in load_entry_point
    return ep.load()
  File "/home/user/.local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2450, in load
    return self.resolve()
  File "/home/user/.local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2456, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/veusz/veusz_main.py", line 32, in <module>
    from veusz import utils
  File "/usr/lib/python3/dist-packages/veusz/utils/__init__.py", line 22, in <module>
    from .textrender import Renderer, FontMetrics, latexEscape
  File "/usr/lib/python3/dist-packages/veusz/utils/textrender.py", line 30, in <module>
    from . import points
  File "/usr/lib/python3/dist-packages/veusz/utils/points.py", line 25, in <module>
    from ..helpers.qtloops import plotPathsToPainter
ValueError: PyCapsule_GetPointer called with incorrect name
user@user-pc:~$ 
```

**Comment by jeremysanders** [comment]
Unfortunately this is a clash between your anaconda python and the system python. The package was built against the system python. PyQt apps need to be compiled with the same version of PyQt and SIP as installed in the python version.

I'm not too familiar with how anaconda does things but you could try
 * Starting veusz with the system python, e.g. `/usr/bin/python3 /usr/bin/veusz`
 * Installing the conda-forge veusz package. I'm not sure if this currently works as there are build problems.
 * Maybe setting up some virtualenv?
 * Running veusz without initialising anaconda

**Comment by deskoop** [comment]
Thanks a lot Jeremy for your reply and this wonderful software. I tried with no success.

In the end, while I fix my anaconda-vs-pip hell, I just [installed via flatpack](https://www.reddit.com/r/Veusz/comments/ndl5m4/veusz_can_now_be_installed_from_flathub_linux/) (thanks! great option!) and it works like a charm :)
Back to plotting!

**Comment by jeremysanders** [comment]
Great
