### ISSUE TITLE
crashed when "Save as"

### ISSUE THREAD

**Issue by deskoop** [veusz/veusz#535]
I installed veusz using flatpak.
I was working in a file (created using the 'normal' version of veusz ie installed using sudo apt install) and when tried to "save as" and I got the "you encountered a bug" window.
I copy here the report:

```
Traceback (most recent call last):
  File "/app/lib/python3.8/site-packages/veusz/windows/mainwindow.py", line 1165, in slotFileSaveAs
    filename = self.fileSaveDialog(filters, _('Save as'))
  File "/app/lib/python3.8/site-packages/veusz/windows/mainwindow.py", line 1121, in fileSaveDialog
    filetype = filetype_re.match(fd.selectedNameFilter()).group(1)
AttributeError: 'NoneType' object has no attribute 'group'

Frame slotFileSaveAs (File /app/lib/python3.8/site-packages/veusz/windows/mainwindow.py, line 1165)
 self = <veusz.windows.mainwindow.MainWindow object at 0x7f5e28a131f0>
  self.AllowNestedDocks = 2
  self.AllowTabbedDocks = 4
  self.AnimatedDocks = 1
  self.DrawChildren = 2
  self.DrawWindowBackground = 1
  self.ForceTabbedDocks = 8
  self.GroupedDragging = 32
  self.IgnoreMask = 4
  self.PdmDepth = 6
  self.PdmDevicePixelRatio = 11
  self.PdmDevicePixelRatioScaled = 12
  self.PdmDpiX = 7
  self.PdmDpiY = 8
  self.PdmHeight = 2
  self.PdmHeightMM = 4
  self.PdmNumColors = 5
  self.PdmPhysicalDpiX = 9
  self.PdmPhysicalDpiY = 10
  self.PdmWidth = 1
  self.PdmWidthMM = 3
  self.VerticalTabs = 16
  self.__dict__ = {'document': <veusz.document.doc.Document object at 0x7f5e155f0af0>, 'filename': '/run/user/1000/doc/f91aad4c/SOD01.vsz'...
  self.__doc__ = ' The main window class for the application.'
  self.__module__ = 'veusz.windows.mainwindow'
  self.axisvalueslabel = <PyQt5.QtWidgets.QLabel object at 0x7f5e1541adc0>
  self.console = <veusz.windows.consolewindow.ConsoleWindow object at 0x7f5e1541a670>
  self.datadock = <veusz.windows.datanavigator.DataNavigatorWindow object at 0x7f5e15412c10>
  self.datatoolbar = <PyQt5.QtWidgets.QToolBar object at 0x7f5e155954c0>
  self.dbusdocinterface = <veusz.document.dbusinterface.DBusInterface object at 0x7f5e143ba880>
  self.dbuswininterface = <veusz.windows.mainwindow.DBusWinInterface object at 0x7f5e143badf0>
  self.dialogs = []
  self.dirname = '/home/user00'
  self.document = <veusz.document.doc.Document object at 0x7f5e155f0af0>
  self.documentsetup = True
  self.filename = '/run/user/1000/doc/f91aad4c/SOD01.vsz'
  self.formatdock = <veusz.windows.treeeditwindow.FormatDock object at 0x7f5e15412b80>
  self.interpreter = <veusz.document.commandinterpreter.CommandInterpreter object at 0x7f5e154370d0>
  self.maintoolbar = <PyQt5.QtWidgets.QToolBar object at 0x7f5e15595790>
  self.menus = {'file': <PyQt5.QtWidgets.QMenu object at 0x7f5e15462d30>, 'file.new': <PyQt5.QtWidgets.QMenu object at 0x7f5e15462dc0>,...
  self.pagelabel = <PyQt5.QtWidgets.QLabel object at 0x7f5e1541ae50>
  self.pickerlabel = <PyQt5.QtWidgets.QLabel object at 0x7f5e1541aca0>
  self.plot = <veusz.windows.plotwindow.PlotWindow object at 0x7f5e1546bd30>
  self.plotqueuecount = 0
  self.plotqueuelabel = <PyQt5.QtWidgets.QLabel object at 0x7f5e1541ad30>
  self.propdock = <veusz.windows.treeeditwindow.PropertiesDock object at 0x7f5e15412940>
  self.recentFileActions = {'filerecent0': <PyQt5.QtWidgets.QAction object at 0x7f5e1429ef70>}
  self.securitylabel = <veusz.qtwidgets.clicklabel.ClickLabel object at 0x7f5e1541aee0>
  self.staticMetaObject = <PyQt5.QtCore.QMetaObject object at 0x7f5dfe7e6f20>
  self.statusbar = <PyQt5.QtWidgets.QStatusBar object at 0x7f5e1541ac10>
  self.treeedit = <veusz.windows.treeeditwindow.TreeEditDock object at 0x7f5e15400700>
  self.viewwinfns = [(<veusz.windows.treeeditwindow.TreeEditDock object at 0x7f5e15400700>, <PyQt5.QtWidgets.QAction object at 0x7f5e155b15e...
  self.vzactions = {'file.new.menu': <PyQt5.QtWidgets.QAction object at 0x7f5e15548160>, 'file.new.graph': <PyQt5.QtWidgets.QAction object ...
  self.windows = [<veusz.windows.mainwindow.MainWindow object at 0x7f5e28a131f0>]
 filters = ['Veusz document files (*.vsz)', 'Veusz HDF5 document files (*.vszh5)']

Frame fileSaveDialog (File /app/lib/python3.8/site-packages/veusz/windows/mainwindow.py, line 1121)
 self = <veusz.windows.mainwindow.MainWindow object at 0x7f5e28a131f0>
 filters = ['Veusz document files (*.vsz)', 'Veusz HDF5 document files (*.vszh5)']
 dialogtitle = 'Save as'
 fd = <PyQt5.QtWidgets.QFileDialog object at 0x7f5e14316040>
 filtertypes = ['vsz', 'vszh5']
 filterkey = 'filterdefault_vsz_vszh5'
 filename = '/run/user/1000/doc/64396579/SOD02.vsz'
 filetype_re = re.compile('.*\\(\\*\\.([a-z0-9]+)\\)')
```

**Comment by deskoop** [comment]
I also noticed two things
1) the "trust" option (File-Trust) was enabled, meaning this was not recognized as a trustable vsz file?
2) when opening the file, a dialog said it can't find the datafile [Errno 2], which was actually there...

**Comment by jeremysanders** [comment]
Does this happen every time you save a document? If so, I'd file a bug with the flatpak packagers. It looks like the file save dialog is not returning a correctly selected filter.
