### ISSUE TITLE
PyCapsule_GetPointer called with incorrect name

### ISSUE THREAD

**Issue by jbeale1** [veusz/veusz#537]
After some confusion about SIP and PyQt5, I have been able to compile and install veusz 3.3.1 on a Raspberry Pi (Linux 5.10.17-v7l+ #1421 SMP Thu May 27 14:00:13 BST 2021) with no errors reported. Specifically, these commands were sucessfull:
```
cd veusz-3.3.1/
python3 setup.py build
sudo python3 setup.py install
```

However, it does not run, and I'm unsure what the error means:
```
pi@rp49:~/Downloads/veusz-3.3.1 $ veusz
Traceback (most recent call last):
  File "/usr/local/bin/veusz", line 11, in <module>
    load_entry_point('veusz==3.3.1', 'gui_scripts', 'veusz')()
  File "/home/pi/.local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 474, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/pi/.local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2846, in load_entry_point
    return ep.load()
  File "/home/pi/.local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2450, in load
    return self.resolve()
  File "/home/pi/.local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2456, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.7/dist-packages/veusz-3.3.1-py3.7-linux-armv7l.egg/veusz/veusz_main.py", line 31, in <module>
    from veusz import qtall as qt
  File "/usr/local/lib/python3.7/dist-packages/veusz-3.3.1-py3.7-linux-armv7l.egg/veusz/qtall.py", line 26, in <module>
    from PyQt5.QtSvg import *
ValueError: PyCapsule_GetPointer called with incorrect name
```

**Comment by jbeale1** [comment]
Apparently this can happen when PyQt5 is a later version than some other package expects and in some cases can be fixed by downgrading PyQt5 (?)  https://stackoverflow.com/questions/55794101/valueerrorpycapsule-getpointer-called-with-incorrect-name-with-from-pyqt5-qtwe

**Comment by jeremysanders** [comment]
Yes - it's caused by sip having a different version when it was compiled compared to when it is running. You probably have more than one sip installed (os package and PyPI?) and these are interacting with each other. Unfortunately you'll need to get rid of one of them and rebuild, or use something like virtual roots.

**Comment by jbeale1** [comment]
Thank you for your prompt response. I tried to follow the advice at https://github.com/veusz/veusz/wiki/DevStart but when trying to use a sandbox, I wasn't able to get past the problem shown below; any opinions welcomed!
```
pi@rp49:~/Downloads/veusz-3.3.1 $ source sandbox/bin/activate
(sandbox) pi@rp49:~/Downloads/veusz-3.3.1 $ pip install numpy sip==5.5.0 PyQt5 
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting numpy
  Using cached https://www.piwheels.org/simple/numpy/numpy-1.21.0-cp37-cp37m-linux_armv7l.whl
Collecting sip==5.5.0
  Using cached https://www.piwheels.org/simple/sip/sip-5.5.0-cp37-cp37m-linux_armv7l.whl
Collecting PyQt5
  Using cached https://files.pythonhosted.org/packages/8e/a4/d5e4bf99dd50134c88b95e926d7b81aad2473b47fde5e3e4eac2c69a8942/PyQt5-5.15.4.tar.gz
  Installing build dependencies ... done
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib/python3.7/tokenize.py", line 447, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-obny50gs/PyQt5/setup.py'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-obny50gs/PyQt5/
```

**Comment by jbeale1** [comment]
EDIT: nevermind, I had pip 18.1 so it turns out **pip3 install --upgrade pip** to get pip-21.1.2 at least got me past that first bump.

**Comment by jbeale1** [comment]
Using a sandbox environment and following https://github.com/veusz/veusz/wiki/DevStart I am able to compile and install apparently without errors, but when I run the program, I don't have PyQt5.QtSvg despite the fact that it seems to already be installed, in that sandbox, as shown below. 

```
(sandbox) pi@rp49:~/Downloads/veusz-3.3.1 $ sudo apt install python3-pyqt5.qtsvg
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python3-pyqt5.qtsvg is already the newest version (5.11.3+dfsg-1+rpi1+b3).
0 upgraded, 0 newly installed, 0 to remove and 13 not upgraded.

(sandbox) pi@rp49:~/Downloads/veusz-3.3.1 $ veusz
Traceback (most recent call last):
  File "/home/pi/Downloads/sandbox/bin/veusz", line 11, in <module>
    load_entry_point('veusz==3.3.1', 'gui_scripts', 'veusz')()
  File "/home/pi/Downloads/sandbox/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/pi/Downloads/sandbox/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "/home/pi/Downloads/sandbox/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2411, in load
    return self.resolve()
  File "/home/pi/Downloads/sandbox/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/pi/Downloads/sandbox/lib/python3.7/site-packages/veusz-3.3.1-py3.7-linux-armv7l.egg/veusz/veusz_main.py", line 31, in <module>
    from veusz import qtall as qt
  File "/home/pi/Downloads/sandbox/lib/python3.7/site-packages/veusz-3.3.1-py3.7-linux-armv7l.egg/veusz/qtall.py", line 26, in <module>
    from PyQt5.QtSvg import *
ModuleNotFoundError: No module named 'PyQt5.QtSvg'

```

**Comment by jbeale1** [comment]
Followed https://github.com/veusz/veusz/wiki/DevStart and got the same PyQt5.QtSvg error, on a fresh install of Ubuntu 20.04.2 LTS. From the sandbox, PyQt5.QtSvg is not available. You can do **apt install python3-pyqt5.qtsvg** but that installs it in the system folder, not in the sandbox.  The line **pip install numpy sip==5.5.0 PyQt5** apparently does not install the QtSvg part of Qt5.
I'm wondering if one of the "optional" steps listed (for astropy, Ghostscript etc. which I didn't do) is in fact not optional, because it brings QtSvg into the sandbox also, as a side effect?
