### ISSUE TITLE
Cannot save project

### ISSUE THREAD

**Issue by cyrilmauclair** [veusz/veusz#555]
Hi, thx for this great soft!
It seems that I can't save my project. When I try that (either using the icon or ctrl+s) here is the dialog box I see
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%ù
raceback (most recent call last):
  File "/app/lib/python3.8/site-packages/veusz/windows/mainwindow.py", line 1067, in slotFileSave
    self.slotFileSaveAs()
  File "/app/lib/python3.8/site-packages/veusz/windows/mainwindow.py", line 1165, in slotFileSaveAs
    filename = self.fileSaveDialog(filters, _('Save as'))
  File "/app/lib/python3.8/site-packages/veusz/windows/mainwindow.py", line 1121, in fileSaveDialog
    filetype = filetype_re.match(fd.selectedNameFilter()).group(1)
AttributeError: 'NoneType' object has no attribute 'group'

Frame slotFileSave (File /app/lib/python3.8/site-packages/veusz/windows/mainwindow.py, line 1067)
 self = <veusz.windows.mainwindow.MainWindow object at 0x7fae2f1ffd30>
  self.AllowNestedDocks = 2
  self.AllowTabbedDocks = 4
  self.AnimatedDocks = 1
  self.DrawChildren = 2
  self.DrawWindowBackground = 1
  self.ForceTabbedDocks = 8
  self.GroupedDragging = 32
  self.IgnoreMask = 4
  self.PdmDepth = 6
  self.PdmDevicePixelRatio = 11
  self.PdmDevicePixelRatioScaled = 12
  self.PdmDpiX = 7
  self.PdmDpiY = 8
  self.PdmHeight = 2
  self.PdmHeightMM = 4
  self.PdmNumColors = 5
  self.PdmPhysicalDpiX = 9
  self.PdmPhysicalDpiY = 10
  self.PdmWidth = 1
  self.PdmWidthMM = 3
  self.VerticalTabs = 16
  self.__dict__ = {'document': <veusz.document.doc.Document object at 0x7fae2f1ff790>, 'filename': '', 'dialogs': [], 'vzactions': {'file....
  self.__doc__ = ' The main window class for the application.'
  self.__module__ = 'veusz.windows.mainwindow'
  self.axisvalueslabel = <PyQt5.QtWidgets.QLabel object at 0x7fae2ce981f0>
  self.console = <veusz.windows.consolewindow.ConsoleWindow object at 0x7fae2ce94af0>
  self.datadock = <veusz.windows.datanavigator.DataNavigatorWindow object at 0x7fae2ce94160>
  self.datatoolbar = <PyQt5.QtWidgets.QToolBar object at 0x7fae2cf6bdc0>
  self.dbusdocinterface = <veusz.document.dbusinterface.DBusInterface object at 0x7fae2e860550>
  self.dbuswininterface = <veusz.windows.mainwindow.DBusWinInterface object at 0x7fae2ce81910>
  self.dialogs = []
  self.dirname = '/app/lib/python3.8/site-packages/veusz/examples'
  self.document = <veusz.document.doc.Document object at 0x7fae2f1ff790>
  self.documentsetup = True
  self.filename = ''
  self.formatdock = <veusz.windows.treeeditwindow.FormatDock object at 0x7fae2ce940d0>
  self.interpreter = <veusz.document.commandinterpreter.CommandInterpreter object at 0x7fae2e860730>
  self.maintoolbar = <PyQt5.QtWidgets.QToolBar object at 0x7fae2cf80ee0>
  self.menus = {'file': <PyQt5.QtWidgets.QMenu object at 0x7fae2ce86430>, 'file.new': <PyQt5.QtWidgets.QMenu object at 0x7fae2ce864c0>,...
  self.pagelabel = <PyQt5.QtWidgets.QLabel object at 0x7fae2ce98280>
  self.pickerlabel = <PyQt5.QtWidgets.QLabel object at 0x7fae2ce980d0>
  self.plot = <veusz.windows.plotwindow.PlotWindow object at 0x7fae2ce8f430>
  self.plotqueuecount = 0
  self.plotqueuelabel = <PyQt5.QtWidgets.QLabel object at 0x7fae2ce98160>
  self.propdock = <veusz.windows.treeeditwindow.PropertiesDock object at 0x7fae2ce93e50>
  self.recentFileActions = {'filerecent0': <PyQt5.QtWidgets.QAction object at 0x7fae2ce985e0>, 'filerecent1': <PyQt5.QtWidgets.QAction object at 0x...
  self.securitylabel = <veusz.qtwidgets.clicklabel.ClickLabel object at 0x7fae2ce98310>
  self.staticMetaObject = <PyQt5.QtCore.QMetaObject object at 0x7fae2c19bac0>
  self.statusbar = <PyQt5.QtWidgets.QStatusBar object at 0x7fae2ce98040>
  self.treeedit = <veusz.windows.treeeditwindow.TreeEditDock object at 0x7fae2ce90430>
  self.viewwinfns = [(<veusz.windows.treeeditwindow.TreeEditDock object at 0x7fae2ce90430>, <PyQt5.QtWidgets.QAction object at 0x7fae2cf8016...
  self.vzactions = {'file.new.menu': <PyQt5.QtWidgets.QAction object at 0x7fae2cf3d940>, 'file.new.graph': <PyQt5.QtWidgets.QAction object ...
  self.windows = [<veusz.windows.mainwindow.MainWindow object at 0x7fae3e5bbaf0>, <veusz.windows.mainwindow.MainWindow object at 0x7fae2f1ffd30>]

Frame slotFileSaveAs (File /app/lib/python3.8/site-packages/veusz/windows/mainwindow.py, line 1165)
 self = <veusz.windows.mainwindow.MainWindow object at 0x7fae2f1ffd30>
 filters = ['Veusz document files (*.vsz)', 'Veusz HDF5 document files (*.vszh5)']

Frame fileSaveDialog (File /app/lib/python3.8/site-packages/veusz/windows/mainwindow.py, line 1121)
 self = <veusz.windows.mainwindow.MainWindow object at 0x7fae2f1ffd30>
 filters = ['Veusz document files (*.vsz)', 'Veusz HDF5 document files (*.vszh5)']
 dialogtitle = 'Save as'
 fd = <PyQt5.QtWidgets.QFileDialog object at 0x7fae2c46ff70>
 filtertypes = ['vsz', 'vszh5']
 filterkey = 'filterdefault_vsz_vszh5'
 filename = '/run/user/1000/doc/926228cc/test'
 filetype_re = re.compile('.*\\(\\*\\.([a-z0-9]+)\\)')

%%%%%%%%%

I'm on linux mint and I have installed Veusz through the software center.

Best regards

**Comment by jeremysanders** [comment]
Strange. Perhaps the behaviour of the file dialog has changed in recent Qt versions.

As a workaround, you could try adding .vsz (or .vszh5) to the end of the filename and see if that helps.

**Comment by cyrilmauclair** [comment]
Thx for answering so quick. I tried that (both extensions), but it does not work and I get the same message (I believe). Here it is if that may help.
%%%%%%%%%%%%%%%%
Traceback (most recent call last):
  File "/app/lib/python3.8/site-packages/veusz/windows/mainwindow.py", line 1067, in slotFileSave
    self.slotFileSaveAs()
  File "/app/lib/python3.8/site-packages/veusz/windows/mainwindow.py", line 1165, in slotFileSaveAs
    filename = self.fileSaveDialog(filters, _('Save as'))
  File "/app/lib/python3.8/site-packages/veusz/windows/mainwindow.py", line 1121, in fileSaveDialog
    filetype = filetype_re.match(fd.selectedNameFilter()).group(1)
AttributeError: 'NoneType' object has no attribute 'group'

Frame slotFileSave (File /app/lib/python3.8/site-packages/veusz/windows/mainwindow.py, line 1067)
 self = <veusz.windows.mainwindow.MainWindow object at 0x7fae2f1ffd30>
  self.AllowNestedDocks = 2
  self.AllowTabbedDocks = 4
  self.AnimatedDocks = 1
  self.DrawChildren = 2
  self.DrawWindowBackground = 1
  self.ForceTabbedDocks = 8
  self.GroupedDragging = 32
  self.IgnoreMask = 4
  self.PdmDepth = 6
  self.PdmDevicePixelRatio = 11
  self.PdmDevicePixelRatioScaled = 12
  self.PdmDpiX = 7
  self.PdmDpiY = 8
  self.PdmHeight = 2
  self.PdmHeightMM = 4
  self.PdmNumColors = 5
  self.PdmPhysicalDpiX = 9
  self.PdmPhysicalDpiY = 10
  self.PdmWidth = 1
  self.PdmWidthMM = 3
  self.VerticalTabs = 16
  self.__dict__ = {'document': <veusz.document.doc.Document object at 0x7fae2f1ff790>, 'filename': '', 'dialogs': [], 'vzactions': {'file....
  self.__doc__ = ' The main window class for the application.'
  self.__module__ = 'veusz.windows.mainwindow'
  self.axisvalueslabel = <PyQt5.QtWidgets.QLabel object at 0x7fae2ce981f0>
  self.console = <veusz.windows.consolewindow.ConsoleWindow object at 0x7fae2ce94af0>
  self.datadock = <veusz.windows.datanavigator.DataNavigatorWindow object at 0x7fae2ce94160>
  self.datatoolbar = <PyQt5.QtWidgets.QToolBar object at 0x7fae2cf6bdc0>
  self.dbusdocinterface = <veusz.document.dbusinterface.DBusInterface object at 0x7fae2e860550>
  self.dbuswininterface = <veusz.windows.mainwindow.DBusWinInterface object at 0x7fae2ce81910>
  self.dialogs = []
  self.dirname = '/app/lib/python3.8/site-packages/veusz/examples'
  self.document = <veusz.document.doc.Document object at 0x7fae2f1ff790>
  self.documentsetup = True
  self.filename = ''
  self.formatdock = <veusz.windows.treeeditwindow.FormatDock object at 0x7fae2ce940d0>
  self.interpreter = <veusz.document.commandinterpreter.CommandInterpreter object at 0x7fae2e860730>
  self.maintoolbar = <PyQt5.QtWidgets.QToolBar object at 0x7fae2cf80ee0>
  self.menus = {'file': <PyQt5.QtWidgets.QMenu object at 0x7fae2ce86430>, 'file.new': <PyQt5.QtWidgets.QMenu object at 0x7fae2ce864c0>,...
  self.pagelabel = <PyQt5.QtWidgets.QLabel object at 0x7fae2ce98280>
  self.pickerlabel = <PyQt5.QtWidgets.QLabel object at 0x7fae2ce980d0>
  self.plot = <veusz.windows.plotwindow.PlotWindow object at 0x7fae2ce8f430>
  self.plotqueuecount = 0
  self.plotqueuelabel = <PyQt5.QtWidgets.QLabel object at 0x7fae2ce98160>
  self.propdock = <veusz.windows.treeeditwindow.PropertiesDock object at 0x7fae2ce93e50>
  self.recentFileActions = {'filerecent0': <PyQt5.QtWidgets.QAction object at 0x7fae2ce985e0>, 'filerecent1': <PyQt5.QtWidgets.QAction object at 0x...
  self.securitylabel = <veusz.qtwidgets.clicklabel.ClickLabel object at 0x7fae2ce98310>
  self.staticMetaObject = <PyQt5.QtCore.QMetaObject object at 0x7fae2c19bcf0>
  self.statusbar = <PyQt5.QtWidgets.QStatusBar object at 0x7fae2ce98040>
  self.treeedit = <veusz.windows.treeeditwindow.TreeEditDock object at 0x7fae2ce90430>
  self.viewwinfns = [(<veusz.windows.treeeditwindow.TreeEditDock object at 0x7fae2ce90430>, <PyQt5.QtWidgets.QAction object at 0x7fae2cf8016...
  self.vzactions = {'file.new.menu': <PyQt5.QtWidgets.QAction object at 0x7fae2cf3d940>, 'file.new.graph': <PyQt5.QtWidgets.QAction object ...
  self.windows = [<veusz.windows.mainwindow.MainWindow object at 0x7fae3e5bbaf0>, <veusz.windows.mainwindow.MainWindow object at 0x7fae2f1ffd30>]

Frame slotFileSaveAs (File /app/lib/python3.8/site-packages/veusz/windows/mainwindow.py, line 1165)
 self = <veusz.windows.mainwindow.MainWindow object at 0x7fae2f1ffd30>
 filters = ['Veusz document files (*.vsz)', 'Veusz HDF5 document files (*.vszh5)']

Frame fileSaveDialog (File /app/lib/python3.8/site-packages/veusz/windows/mainwindow.py, line 1121)
 self = <veusz.windows.mainwindow.MainWindow object at 0x7fae2f1ffd30>
 filters = ['Veusz document files (*.vsz)', 'Veusz HDF5 document files (*.vszh5)']
 dialogtitle = 'Save as'
 fd = <PyQt5.QtWidgets.QFileDialog object at 0x7fae2c46ff70>
 filtertypes = ['vsz', 'vszh5']
 filterkey = 'filterdefault_vsz_vszh5'
 filename = '/run/user/1000/doc/eed0d134/test.vsz'
 filetype_re = re.compile('.*\\(\\*\\.([a-z0-9]+)\\)')

**Comment by jeremysanders** [comment]
Strange. Do you know what version of Qt is installed on your Linux version? I think you could look up the libqt5core5a package version (or give the Mint version and I can probably find it out). Maybe I should updating my Ubuntu to see if it's the same problem.

Other workarounds
 * If you bring up the command line console, you should be able to do `Save('filename.vsz')` to save the document (a path may need to be given)
 * The binary version should work as it ships its own Qt

**Comment by cyrilmauclair** [comment]
Thx for your reply: the libqt5core5a version is 5.12.8+dfsg-0ubuntu1
Thx for the command line workaround, it works!
I'll try the binary version too, but I'm happy I can already record everything now ;)
