### ISSUE TITLE
KeyError on opening file, Error name is a dataset name

### ISSUE THREAD

**Issue by Tragula** [veusz/veusz#577]
Hello!
When I try to load one of my files, I get this error message:

![Error Screenshot](https://user-images.githubusercontent.com/90611500/148060188-f68e8367-ee71-43d6-b616-3ff7320c24e9.jpg)
Error Text:
```
Traceback (most recent call last):
  File "veusz\document\loader.py", line 157, in executeScript
  File "C:\Users\Marius\Desktop\#12_plots.vsz", line 32, in <module>
    TagDatasets(u'process_#12', [u'set24_?', u'set24_BTM_g/L', u'set24_CER', u'set24_GV', u'set24_N', u'set24_No_sample', u'set24_OD', u'set24_OUR', u'set24_P', u'set24_RQ', u'set24_RQ_sum', u'set24_VG', u'set24_V_F1_sum', u'set24_V_F1_sum_pls', u'set24_V_F2_sum', u'set24_V_F2_sum_pls', u'set24_V_R', u'set24_V_R_pls', u'set24_V_base_sum', u'set24_V_base_sum_pls', u'set24_V_sample', u'set24_YCO2s', u'set24_YCO2s_mol', u'set24_YCO2x', u'set24_YCO2x_mmol', u'set24_YO2s', u'set24_YO2s_mol', u'set24_YO2x', u'set24_YO2x_mmol', u'set24_Yacs', u'set24_Yacs_mol', u'set24_Yacx', u'set24_Yacx_mmol', u'set24_Ymets', u'set24_Ymets_mol', u'set24_Ymetx', u'set24_Ymetx_mmol', u'set24_Yxs', u'set24_Yxs_mol', u'set24_c_NH4_g/L', u'set24_c_PO4_g/L', u'set24_c_ac_g/L', u'set24_c_citr_g/L', u'set24_c_form_g/L', u'set24_c_glc_g/L', u'set24_c_mal_g/L', u'set24_c_met_g/L', u'set24_c_succ_g/L', u'set24_c_x_Cmol/L', u'set24_c_x_g/L', u'set24_c_x_mol/L', u'set24_clock', u'set24_interterval_span', u'set24_interval_name_long', u'set24_interval_name_short', u'set24_kla', u'set24_m_F1_pls', u'set24_m_F2_pls', u'set24_m_base', u'set24_m_x_Cmol', u'set24_m_x_g', u'set24_m_x_mol', u'set24_pH', u'set24_pO2', u'set24_produ_CO2_sum', u'set24_produ_CO2_sum_Cmol', u'set24_produ_CO2_sum_g', u'set24_produ_CO2_sum_mol', u'set24_produ_CO2_sum_pls', u'set24_produ_ac_Cmol', u'set24_produ_ac_g', u'set24_produ_ac_mol', u'set24_produ_citr_Cmol', u'set24_produ_citr_g', u'set24_produ_citr_mol', u'set24_produ_form_Cmol', u'set24_produ_form_g', u'set24_produ_form_mol', u'set24_produ_mal_Cmol', u'set24_produ_mal_g', u'set24_produ_mal_mol', u'set24_produ_met_Cmol', u'set24_produ_met_g', u'set24_produ_met_mol', u'set24_produ_succ_Cmol', u'set24_produ_succ_g', u'set24_produ_succ_mol', u'set24_qCO2', u'set24_qCO2_mmol', u'set24_qO2', u'set24_qO2_mmol', u'set24_qac', u'set24_qac_mmol', u'set24_qglc', u'set24_qglc_mmol', u'set24_qmet', u'set24_qmet_mmol', u'set24_t_dur_interval', u'set24_t_end_interval', u'set24_t_pls_h', u'set24_t_pls_min', u'set24_t_sample', u'set24_t_start_interval', u'set24_tc_bio_g/L', u'set24_tc_bio_mol/L', u'set24_tc_sup_g/L', u'set24_tc_sup_mol/L', u'set24_tc_sus_g/L', u'set24_tc_sus_mol/L', u'set24_temp', u'set24_tic_bio_g/L', u'set24_tic_bio_mol/L', u'set24_tic_sup_g/L', u'set24_tic_sup_mol/L', u'set24_tic_sus_g/L', u'set24_tic_sus_mol/L', u'set24_tn_bio_g/L', u'set24_tn_bio_mol/L', u'set24_tn_sup_g/L', u'set24_tn_sup_mol/L', u'set24_tn_sus_g/L', u'set24_tn_sus_mol/L', u'set24_toc_bio_g/L', u'set24_toc_bio_mol/L', u'set24_toc_sup_g/L', u'set24_toc_sup_mol/L', u'set24_toc_sus_g/L', u'set24_toc_sus_mol/L', u'set24_uptk_NH4_Cmol', u'set24_uptk_NH4_g', u'set24_uptk_NH4_mol', u'set24_uptk_O2_sum', u'set24_uptk_O2_sum_Cmol', u'set24_uptk_O2_sum_g', u'set24_uptk_O2_sum_mol', u'set24_uptk_O2_sum_pls', u'set24_uptk_PO4_Cmol', u'set24_uptk_PO4_g', u'set24_uptk_PO4_mol', u'set24_uptk_glc_Cmol', u'set24_uptk_glc_g', u'set24_uptk_glc_mol', u'set24_y_CO2%', u'set24_y_O2%'])
  File "veusz\document\commandinterface.py", line 852, in TagDatasets
  File "veusz\document\doc.py", line 182, in applyOperation
  File "veusz\document\operations.py", line 928, in do
KeyError: 'set24_c_mal_g/L'
```
It seems to be related to dataset tagging. As error name it gives out the name of one of the included datasets (you can see it appear in the list in line 12 of the message).
Since I created the file over a year ago on an older version, I tried opening it on V3.1 as well as 3.4 but got the same error (the message shown here is from 3.1). Confirming the error lands me on a blank untitled document, with the exception that all datasets I previously used are already imported. I am using the Windows versions, this error occured on two different Windows 10 machines with this file. Other files that do not include this dataset behave normally.
Help would be much appreciated.

Thanks and best regards

**Comment by jeremysanders** [comment]
Thanks for the report. I don't know what caused the problem, but to avoid the issue you could edit the .vsz file in text editor and remove the line which is giving the error.
