### ISSUE TITLE
ModuleNotFound: `sipbuild` dependency 

### ISSUE THREAD

**Issue by freiburgermsu** [veusz/veusz#592]
I receive the following error when I attempt to `pip install Veusz`
```console
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\Andrew Freiburger\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Andrew Freiburger\\AppData\\Local\\Temp\\pip-install-i7om5irs\\veusz_debea1ffdea5400997d398b55c08573e\\setup.py'"'"'; __file__='"'"'C:\\Users\\Andrew Freiburger\\AppData\\Local\\Temp\\pip-install-i7om5irs\\veusz_debea1ffdea5400997d398b55c08573e\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Andrew Freiburger\AppData\Local\Temp\pip-pip-egg-info-zqryxxby'
         cwd: C:\Users\Andrew Freiburger\AppData\Local\Temp\pip-install-i7om5irs\veusz_debea1ffdea5400997d398b55c08573e\
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Andrew Freiburger\AppData\Local\Temp\pip-install-i7om5irs\veusz_debea1ffdea5400997d398b55c08573e\setup.py", line 35, in <module>
        import pyqtdistutils
      File "C:\Users\Andrew Freiburger\AppData\Local\Temp\pip-install-i7om5irs\veusz_debea1ffdea5400997d398b55c08573e\pyqtdistutils.py", line 15, in <module>
        from sipbuild.code_generator import set_globals, parse, generateCode
    ModuleNotFoundError: No module named 'sipbuild'
```
and I receive the following error when I attempt to separately install `sipbuild`:
```console
ERROR: Could not find a version that satisfies the requirement sipbuild (from versions: none)
ERROR: No matching distribution found for sipbuild
```
How can the Python module `Veusz` be install? Only from the source after cloning the repository?

**Comment by korintje** [comment]
As far as I know, installation by `pip` is still under development, as discussed in the following issue.
https://github.com/veusz/veusz/issues/351, https://github.com/veusz/veusz/issues/457

Therefore, as you say, it must be built from source or installed by `conda` so far.

**Comment by korintje** [comment]
Also, you can use Veusz executable from your python script with `embed.py` as described below:

https://github.com/veusz/veusz/issues/457
> However, you can install the veusz executable and take the embed.py part of veusz and use this directly in your program. embed.py talks to the main veusz executable via a socket, so it can run in a separate process.. embed.py doesn't use Qt directly You just need to have the veusz executable on your path before using it (e.g. modify os.environ['PATH'] to also include this directory).

**Comment by StSav012** [comment]
On Fedora, I had to install `sip6` to provide the module and then `python3-qt5-devel` to conquer another problem.
