### ISSUE TITLE
Can not build from source: ImportError: cannot import name 'parse' from 'sipbuild.code_generator'

### ISSUE THREAD

**Issue by 0range0range** [veusz/veusz#595]
Hello, 
I am having problems running recent version of veusz on Arch linux.

Here is the link to the package I have installed: 
https://aur.archlinux.org/packages/veusz

When i try to start the program I get the following error:
```
Traceback (most recent call last):
  File "/usr/bin/veusz", line 33, in <module>
    sys.exit(load_entry_point('veusz==3.4', 'gui_scripts', 'veusz')())
  File "/usr/bin/veusz", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 957, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 548, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for veusz
```
Is this problem specific to the veusz itself or the OS?

**Comment by medmedin2014** [comment]
@0range0range For me v3.4 is working fine on Manjaro KDE.

**Comment by 0range0range** [comment]
Although for now I am using Linux binary solution and it runs, installing with a package manager (yay) from AUR still does not work. Also I could not build it from source.

# When building from source with latest sip (6.6.2-1):

```bash
Traceback (most recent call last):
  File "/home/user/No_package_manager_installs/builds/veusz-veusz-3.4/setup.py", line 35, in <module>
    import pyqtdistutils
  File "/home/user/No_package_manager_installs/builds/veusz-veusz-3.4/pyqtdistutils.py", line 15, in <module>
    from sipbuild.code_generator import set_globals, parse, generateCode
ImportError: cannot import name 'parse' from 'sipbuild.code_generator' (/usr/lib/python3.10/site-packages/sipbuild/code_generator.abi3.so)
~/No_package_manager_installs/builds/veusz-veusz-3.4
```

# When building from source with sip-65:
```bash
building 'veusz.helpers.threed' extension
Traceback (most recent call last):
  File "/home/user/No_package_manager_installs/builds/veusz-veusz-3.4/setup.py", line 102, in <module>
    setup(
  File "/usr/lib/python3.10/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 148, in setup
    return run_commands(dist)
  File "/usr/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
    dist.run_commands()
  File "/usr/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.10/site-packages/setuptools/dist.py", line 1214, in run_command
    super().run_command(command)
  File "/usr/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/usr/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.10/site-packages/setuptools/dist.py", line 1214, in run_command
    super().run_command(command)
  File "/usr/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/home/user/No_package_manager_installs/builds/veusz-veusz-3.4/pyqtdistutils.py", line 286, in build_extensions
    distutils.command.build_ext.build_ext.build_extensions(self)
  File "/usr/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/usr/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "/usr/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 506, in build_extension
    sources = self.swig_sources(sources, ext)
  File "/home/user/No_package_manager_installs/builds/veusz-veusz-3.4/pyqtdistutils.py", line 218, in swig_sources
    self._sip_compile(sip, sip_builddir)
  File "/home/user/No_package_manager_installs/builds/veusz-veusz-3.4/pyqtdistutils.py", line 252, in _sip_compile
    pt, _fq_name, _uses_limited_api, _sip_files, tags, disabled_features = parse(
  File "/usr/lib/python3.10/site-packages/sipbuild/helpers.py", line 59, in get_bindings_configuration
    cfg_abi_major = int(resolve_abi_version(cfg_abi_version).split('.')[0])
  File "/usr/lib/python3.10/site-packages/sipbuild/module/abi_version.py", line 106, in resolve_abi_version
    raise UserException(f"'{abi_version}' is not a supported ABI version")
sipbuild.exceptions.UserException
```

# AUR package

Also could not build neither `veusz` nor `veusz-git` (https://aur.archlinux.org/packages/veusz / https://aur.archlinux.org/packages/veusz-git) from AUR repositories.
Following suggestion in comments from here (https://aur.archlinux.org/packages/veusz) i replaced my currently installed version of sip by sip-65.


When trying to build with a package manager (yay):

## veusz-git (sip-version 6.6):

```bash
=> Starting build()...
Traceback (most recent call last):
  File "/home/user/.cache/yay/veusz-git/src/veusz/setup.py", line 35, in <module>
    import pyqtdistutils
  File "/home/user/.cache/yay/veusz-git/src/veusz/pyqtdistutils.py", line 15, in <module>
    from sipbuild.code_generator import set_globals, parse, generateCode
ImportError: cannot import name 'parse' from 'sipbuild.code_generator' (/usr/lib/python3.10/site-packages/sipbuild/code_generator.abi3.so)
==> ERROR: A failure occurred in build().
```

## veusz (automatically replaces latest sip with sip-65):

```bash
building 'veusz.helpers.threed' extension
Traceback (most recent call last):
  File "/home/user/.cache/yay/veusz/src/veusz-3.4/setup.py", line 102, in <module>
    setup(
  File "/usr/lib/python3.10/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 148, in setup
    return run_commands(dist)
  File "/usr/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
    dist.run_commands()
  File "/usr/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.10/site-packages/setuptools/dist.py", line 1214, in run_command
    super().run_command(command)
  File "/usr/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/usr/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.10/site-packages/setuptools/dist.py", line 1214, in run_command
    super().run_command(command)
  File "/usr/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/home/user/.cache/yay/veusz/src/veusz-3.4/pyqtdistutils.py", line 286, in build_extensions
    distutils.command.build_ext.build_ext.build_extensions(self)
  File "/usr/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/usr/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "/usr/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 506, in build_extension
    sources = self.swig_sources(sources, ext)
  File "/home/user/.cache/yay/veusz/src/veusz-3.4/pyqtdistutils.py", line 218, in swig_sources
    self._sip_compile(sip, sip_builddir)
  File "/home/user/.cache/yay/veusz/src/veusz-3.4/pyqtdistutils.py", line 252, in _sip_compile
    pt, _fq_name, _uses_limited_api, _sip_files, tags, disabled_features = parse(
  File "/usr/lib/python3.10/site-packages/sipbuild/helpers.py", line 59, in get_bindings_configuration
    cfg_abi_major = int(resolve_abi_version(cfg_abi_version).split('.')[0])
  File "/usr/lib/python3.10/site-packages/sipbuild/module/abi_version.py", line 106, in resolve_abi_version
    raise UserException(f"'{abi_version}' is not a supported ABI version")
sipbuild.exceptions.UserException
```

Did someone encounter something like this? Of course I could use the binary further, but would be more convenient to use it with a package manager. It seems that simila problems are encountered when installing from AUR and when building from source, so it does not seem to be a packaging problem.

**Comment by sizeofvoid** [comment]
```
===> veusz-3.4p0 depends on: py3-sip-* -> py3-sip-6.6.2v0
===> veusz-3.4p0 depends on: py3-numpy-* -> py3-numpy-1.19.5p1
===> veusz-3.4p0 depends on: py3-qt5-* -> py3-qt5-5.15.7
===> veusz-3.4p0 depends on: python->=3.9,<3.10 -> python-3.9.13p0
===> veusz-3.4p0 depends on: py3-setuptools-* -> py3-setuptools-57.4.0p0v0
===> veusz-3.4p0 depends on: qttools-* -> qttools-5.15.5
===> veusz-3.4p0 depends on: qtbase-* -> qtbase-5.15.5
===>  Verifying specs:  c++ c++abi pthread Qt5Core Qt5Gui Qt5Widgets Qt5Xml m
===>  found c++.9.0 c++abi.6.0 pthread.26.1 Qt5Core.3.1 Qt5Gui.3.0 Qt5Widgets.4.0 Qt5Xml.3.0 m.10.1
===>  Checking files for veusz-3.4p0
`/mnt/wd0/distfiles/veusz-3.4.tar.gz' is up to date.
>> (SHA256) veusz-3.4.tar.gz: OK
===>  Extracting for veusz-3.4p0
===>  Patching for veusz-3.4p0
===>  Compiler link: clang -> /usr/bin/clang
===>  Compiler link: clang++ -> /usr/bin/clang++
===>  Compiler link: cc -> /usr/bin/cc
===>  Compiler link: c++ -> /usr/bin/c++
===>  Generating configure for veusz-3.4p0
===>  Configuring for veusz-3.4p0
===>  Building for veusz-3.4p0
Traceback (most recent call last):
  File "/usr/ports/pobj/veusz-3.4/veusz-3.4/./setup.py", line 35, in <module>
    import pyqtdistutils
  File "/usr/ports/pobj/veusz-3.4/veusz-3.4/pyqtdistutils.py", line 15, in <module>
    from sipbuild.code_generator import set_globals, parse, generateCode
ImportError: cannot import name 'parse' from 'sipbuild.code_generator' (/usr/local/lib/python3.9/site-packages/sipbuild/code_generator.abi3.so)
Traceback (most recent call last):
  File "/usr/ports/pobj/veusz-3.4/veusz-3.4/./setup.py", line 35, in <module>
    import pyqtdistutils
  File "/usr/ports/pobj/veusz-3.4/veusz-3.4/pyqtdistutils.py", line 15, in <module>
    from sipbuild.code_generator import set_globals, parse, generateCode
ImportError: cannot import name 'parse' from 'sipbuild.code_generator' (/usr/local/lib/python3.9/site-packages/sipbuild/code_generator.abi3.so)
*** Error 1 in . (/usr/ports/lang/python/python.port.mk:286 'do-build': @: ;[ -e /usr/ports/pobj/veusz-3.4/veusz-3.4/setup.py ] ||  echo 'fr...)
*** Error 2 in . (/usr/ports/infrastructure/mk/bsd.port.mk:2964 '/usr/ports/pobj/veusz-3.4/.build_done': @cd /usr/ports/math/veusz && PKGPAT...)
*** Error 2 in /usr/ports/math/veusz (/usr/ports/infrastructure/mk/bsd.port.mk:2608 'all': @lock=veusz-3.4p0;  export _LOCKS_HELD=" veusz-3....)

```
I see the same issue with 6.6.2

**Comment by jeremysanders** [comment]
This is due to the current build system of Veusz being a hack which relies on some sip internals.

Unfortunately, it's not clear to me how to fix this. If someone is an experienced Python packager, perhaps they could lend a hand?

**Comment by swt2c** [comment]
This is how I updated wxPython to use sip 6.6.2:
https://github.com/wxWidgets/Phoenix/commit/90171ba21659c3d9c51a478188eb1099ec382645

Basically, it dynamically writes out a pyproject.toml and then calls `sip-build --no-compile` which generates the .cpp files from the .sip files (but doesn't try to compile them, which is done by wxPython's existing build system).

**Comment by jeremysanders** [comment]
@swt2c Thanks - that seems an interesting idea - I will take a look

**Comment by jeremysanders** [comment]
The above two commits (sorry, should have put this in a branch) seem to fix the problem well on Linux for me (and presumably other Unix systems). Thanks to @swt2c for the suggestion to make a `pyproject.toml` and run `sip-build`.

Unfortunately there's an issue on the CI for Windows. I think the backslashes are not being written or read correctly in the `pyproject.toml`. I'm travelling and don't have access to my Windows development environment, so I can't investigate this and make a new release. However, probably including the above as a patch should get the current version to build with new sip versions.

**Comment by swt2c** [comment]
@jeremysanders I ran into the same problem with wxPython on Windows.  I believe the solution was to use *single quotes* in the TOML in cases where a path is used.  For example, `sip-files-dir="{srcdir}"` -> `sip-files-dir='{srcdir}'`.

**Comment by korintje** [comment]
@jeremysanders @swt2c
Thank you for the update.
I have confirmed that the updated source can be successfully built also on macOS 12.4.

**Comment by jeremysanders** [comment]
I managed to fix the Windows build (https://github.com/veusz/veusz/commit/e7e045811bf616449da48df2b32129a66397f6ad). It appears toml has a bug where it can't properly encode `r'\x'`, as in`r'foo\x64\bar'`: https://github.com/uiri/toml/issues/404
