### ISSUE TITLE
External plugin: name 'datasetplugin' is not defined

### ISSUE THREAD

**Issue by ikost** [veusz/veusz#614]
Hi Jeremy,

after some time I came back to my old plugins for data import, but found issue when using them. The Veusz starts normal but when I run the import button, I get the following error:

```
File "<string>", line 27, in doImport
NameError: name 'datasetplugin' is not defined
```

Here is a short example code of the plugin 'test.py' for testing:

```
from veusz.plugins import *

class Example(ImportPlugin):

    name = "Example"
    author = "I"
    description = "Does something"
    promote_tab='Test import'

    def __init__(self):
        self.fields = [
        ]

    def doImport(self, params):
        print("OK")
        return [
            datasetplugin.Constant("testconst", "42")
        ]

importpluginregistry.append(Example)

```

Could it be that the way import of detasetplugin works, has been changed recently? Thank you in advance!
Regards,
Ilya

**Comment by jeremysanders** [comment]
It works on my test system, although I need to rename the plugin option on the command line as it conflicts with a qt option.

Does your plugin work if you add

    from veusz.plugins import datasetplugin

to the top of your file?

**Comment by ikost** [comment]
Which option do you have to change?


This code 
```
from veusz.plugins import datasetplugin,importpluginregistry,ImportPlugin

class Example(ImportPlugin):
    """An example plugin for reading a set of unformatted numbers
    from a file."""

    name = "Example p"
    author = "IK"
    description = "Reads a list of numbers in a text file"
    promote_tab='Test import'

    def __init__(self):
        self.fields = [
        ]

    def doImport(self, params):
        """Actually import data
        params is a ImportPluginParams object.
        Return a list of datasetplugin.Dataset1D, datasetplugin.Dataset2D objects
        """
        print("OK")



        return [
            datasetplugin.Constant("testconst", "42"),
            datasetplugin.Function("testfunc(x)", "testconst*x**2")
        ]

importpluginregistry.append(Example)

```



gives the same error:
```
Traceback (most recent call last):
  File "veusz/dialogs/importdialog.py", line 274, in slotImport
  File "veusz/dataimport/dialog_plugin.py", line 179, in doImport
  File "veusz/document/doc.py", line 204, in applyOperation
  File "veusz/dataimport/base.py", line 274, in do
  File "veusz/dataimport/defn_plugin.py", line 101, in doImport
  File "<string>", line 27, in doImport
NameError: name 'datasetplugin' is not defined
```



PS I am on macOS 12.5.1 (M1 chip)

**Comment by jeremysanders** [comment]
Strange. If you add it as a separate import line under the original, does that work? It's weird the symbol is imported at the top, but it is not defined below.

**Comment by korintje** [comment]
I guess (not yet confirmed) that it may be same as the issue below:
https://github.com/veusz/veusz/issues/575#issue-1052111135

If so, I believe it has already been solved at the latest source, but not yet at the latest binary release.

@ikost
Can you try the code below?
In my case, it is effective for the work around at Veusz 3.4

```
from veusz.plugins import datasetplugin,importpluginregistry,ImportPlugin

class Example(ImportPlugin):
    """An example plugin for reading a set of unformatted numbers
    from a file."""

    name = "Example p"
    author = "IK"
    description = "Reads a list of numbers in a text file"
    promote_tab='Test import'

    def __init__(self):
        from veusz.plugins import datasetplugin,importpluginregistry,ImportPlugin
        self.fields = [
        ]

    def doImport(self, params):
        """Actually import data
        params is a ImportPluginParams object.
        Return a list of datasetplugin.Dataset1D, datasetplugin.Dataset2D objects
        """
       from veusz.plugins import datasetplugin,importpluginregistry,ImportPlugin
        print("OK")



        return [
            datasetplugin.Constant("testconst", "42"),
            datasetplugin.Function("testfunc(x)", "testconst*x**2")
        ]

importpluginregistry.append(Example)

```

**Comment by ikost** [comment]
@korintje Yes, now it works fine! Thank you!

**Comment by ikost** [comment]
@korintje It also works without import line in the `__init__` but just with the import line in the `doImport` function.

Let me also drop a short additional note. Maybe it makes sense to put this code (a bit changed) in an example folder as it is not 100% clear on how to write plugins from the example plugin in the main code. For instance, the original example is operating with imports like 
```
from . import datasetplugin
```
What do you think?

**Comment by korintje** [comment]
The wiki page below describes how to write Import plugins. 
https://github.com/veusz/veusz/wiki/ImportPlugins

But, as you say, it is hard to find (plus there is no mention of "tools plugin"), so I think the Documentation needs to be improved. Providing example files sounds also good to me.

I would like to follow Jeremy's opinion on this, as I do not have enough knowledge on Veusz plugin ecosystem history and the final vision.

**Comment by jeremysanders** [comment]
Tools plugins are documented here: https://github.com/veusz/veusz/wiki/ToolsPlugins

I think the original bug is due to a pyinstaller issue where submodules are not imported the same way as outside of pyinstaller.  The binary builds use pyinstaller. I've added some explicit imports in the `__init__.py` file in plugins to fix this.

I've also renamed the `--plugin` command line option to `--veusz-plugin` as Qt seems to intercept `--plugin`.
