### ISSUE TITLE
Build from AUR fails on Manjaro

### ISSUE THREAD

**Issue by medmedin2014** [veusz/veusz#633]
Trying to upgrade from 3.4-3  -> 3.5.3-1 https://aur.archlinux.org/packages/veusz
```
building 'veusz.helpers.threed' extension
Traceback (most recent call last):
  File "/usr/bin/sip-build", line 33, in <module>
    sys.exit(load_entry_point('sip==6.7.3', 'console_scripts', 'sip-build')())
  File "/usr/bin/sip-build", line 25, in importlib_load_entry_point
    return next(matches).load()
StopIteration
Traceback (most recent call last):
  File "/home/mohamed/.cache/yay/veusz/src/veusz-3.5.3/setup.py", line 102, in <module>
    setup(
  File "/usr/lib/python3.10/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/usr/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/usr/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 973, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.10/site-packages/setuptools/dist.py", line 1217, in run_command
    super().run_command(command)
  File "/usr/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 992, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.10/site-packages/setuptools/command/build.py", line 24, in run
    super().run()
  File "/usr/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 132, in run
    self.run_command(cmd_name)
  File "/usr/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.10/site-packages/setuptools/dist.py", line 1217, in run_command
    super().run_command(command)
  File "/usr/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 992, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 346, in run
    self.build_extensions()
  File "/home/mohamed/.cache/yay/veusz/src/veusz-3.5.3/pyqtdistutils.py", line 294, in build_extensions
    distutils.command.build_ext.build_ext.build_extensions(self)
  File "/usr/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 466, in build_extensions
    self._build_extensions_serial()
  File "/usr/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 492, in _build_extensions_serial
    self.build_extension(ext)
  File "/usr/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 525, in build_extension
    sources = self.swig_sources(sources, ext)
  File "/home/mohamed/.cache/yay/veusz/src/veusz-3.5.3/pyqtdistutils.py", line 213, in swig_sources
    self._sip_compile(sip, sip_builddir)
  File "/home/mohamed/.cache/yay/veusz/src/veusz-3.5.3/pyqtdistutils.py", line 278, in _sip_compile
    subprocess.check_call([build_cmd, '--no-compile'], cwd=sip_builddir)
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/sip-build', '--no-compile']' returned non-zero exit status 1.
==> ERROR: A failure occurred in build().
    Aborting...
 -> error making: veusz
```

**Comment by jeremysanders** [comment]
Strange. If you try running the `sip-build` command by hand, does it give any kind of error? It seems like that command is failing for some reason.

**Comment by medmedin2014** [comment]
@jeremysanders It gives the following result:
```
[med@manjaro-med ~]$ /usr/bin/sip-build 
Traceback (most recent call last):
  File "/usr/bin/sip-build", line 33, in <module>
    sys.exit(load_entry_point('sip==6.7.3', 'console_scripts', 'sip-build')())
  File "/usr/bin/sip-build", line 25, in importlib_load_entry_point
    return next(matches).load()
StopIteration
```

**Comment by jeremysanders** [comment]
I think there's a problem with sip-build on your computer, rather than with veusz. If I search for similar errors in google, it says that it can be due to multiple conflicting copies of a python package. Perhaps you have a system package and your own installed at once?
