### ISSUE TITLE
issues with batch mode

### ISSUE THREAD

**Issue by BKFCAW** [veusz/veusz#662]
I now have a streamlined project for which I'd like to run Veusz on the command line without to a pdf file, rather than opening the interface (which is otherwise extremely helpful for development!!!).  I created a test.vsz version of a file that runs without errors, with 2 additional lines at the end:

```
Export("test.pdf")
Quit()
```

I run the following command at the prompt:

```
veusz --listen < test.vsz
```

When I do this, I get the following:

```
SAMP: could not connect to hub
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/veusz/document/commandinterpreter.py", line 150, in run
    c = compile(inputcmds, filename, stattype)
  File "<string>", line 2
    
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/veusz/document/commandinterpreter.py", line 150, in run
    c = compile(inputcmds, filename, stattype)
  File "<string>", line 2
    
SyntaxError: invalid syntax
['heat']
'page1'
'graph1'
'x'
'y'
'colorbar1'
'function1'
'function2'
'image1'
```

The first 'SAMP' message may be related to an 'exec' line in the file - not sure what it means.  For the rest, I don't understand the syntax error message when the original file runs interactively with no errors.

I also noticed that Veusz starts to open an interactive window, then doesn't.

In the end, it appears to create an OK pdf file (very different size from the pdf file from the interactive session, but I don't see a difference visually), but the presence of these messages makes me nervous about going to full production command-line mode.  Do I need to fix something?

**Comment by jeremysanders** [comment]
The listen mode opens a window. This can be worked around by telling Qt to not render by setting `QT_QPA_PLATFORM=minimal`.

In listen mode, all commands need to be on a single line, so it's not suitable for reading vsz files, which contain multi-line commands. However, you could try something like this to load the document
```
Load('in.vsz')
Export('out.png')
Quit()
```

The SAMP message is just a warning. Probably it shouldn't be shown.

The best way to render vsz files is simply using the export option, which shouldn't open up a Window:

```
veusz --export out.png in.vsz
````

**Comment by BKFCAW** [comment]
In that regard, slightly related:

I find that the exec/open command requires the full path, and not just a 
file in the present directory, as is the case for data files.  This 
makes the Veusz .vsz file non-portable.  Is there a way around this?

**Comment by BKFCAW** [comment]
Figured out a solution, perhaps not the most efficient:

```

import os
absolute_path = os.path.dirname(__file__)
relative_path = "titleblock.vsz"
full_path = os.path.join(absolute_path, relative_path)
exec(open(full_path).read())
```

In that regard, slightly related:

I find that the exec/open command requires the full path, and not just a 
file in the present directory, as is the case for data files.  This 
makes the Veusz .vsz file non-portable.  Is there a way around this?
