### ISSUE TITLE
Curve fitting with problem

### ISSUE THREAD

**Issue by Lifan97** [veusz/veusz#688]
I'm using Veusz on Windows. When I fit a nonlinear curve, the following errors occured. I have searched in FAQs for similar issues but the methods mentioned there didn't work. Anyone can help? 

Fitting via Minuit:
<string>:1: RuntimeWarning: invalid value encountered in power
    1      nan     1.22      3.4 
    2      nan      nan      3.4 
    3      nan      nan      3.4 
    4      nan      nan      3.4 
    5      nan      nan      3.4 
    6      nan      nan      3.4 
    7      nan      nan      3.4 
    8      nan     1.22      nan 
    9      nan     1.22      nan 
   10      nan     1.22      nan 
   11      nan     1.22      nan 
   12      nan     1.22      nan 
   13      nan     1.22      nan 
   14      nan      nan      nan 
   15      nan      nan      nan 
   16      nan      nan      nan 
   17      nan      nan      nan 
   18      nan      nan      nan 
   19      nan      nan      nan 
   20      nan      nan      nan 
   21      nan      nan      nan 
   22      nan      nan      nan 
   23      nan      nan      nan 
   24      nan      nan      nan 
   25      nan      nan      nan 
   26      nan      nan      nan 
   27      nan      nan      nan 
   28      nan      nan      nan 
   29      nan      nan      nan 
   30      nan      nan      nan 
   31      nan      nan      nan 
   32      nan      nan      nan 
   33      nan      nan      nan 
   34      nan      nan      nan 
   35      nan      nan      nan 
   36      nan      nan      nan 
   37      nan     1.22      3.4 
   38      nan      nan      3.4 
   39      nan      nan      3.4 
   40      nan      nan      3.4 
   41      nan      nan      3.4 
   42      nan      nan      3.4 
   43      nan      nan      3.4 
   44      nan      nan      3.4 
   45      nan      nan      3.4 
   46      nan      nan      3.4 
   47      nan      nan      3.4 
   48      nan     1.22      nan 
   49      nan     1.22      nan 
   50      nan     1.22      nan 
   51      nan     1.22      nan 
   52      nan     1.22      nan 
   53      nan     1.22      nan 
   54      nan     1.22      nan 
   55      nan     1.22      nan 
   56      nan     1.22      nan 
   57      nan     1.22      nan 
   58      nan      nan      3.4 
   59      nan      nan      3.4 
   60      nan      nan      3.4 
   61      nan      nan      3.4 
   62      nan     1.22      nan 
   63      nan     1.22      nan 
   64      nan     1.22      nan 
   65      nan     1.22      nan 
   66      nan      nan      nan 
   67      nan     1.22      3.4 
   68      nan      nan      3.4 
   69      nan      nan      3.4 
   70      nan      nan      3.4 
   71      nan      nan      3.4 
   72      nan      nan      3.4 
   73      nan      nan      3.4 
   74      nan     1.22      nan 
   75      nan     1.22      nan 
   76      nan     1.22      nan 
   77      nan     1.22      nan 
   78      nan     1.22      nan 
   79      nan     1.22      nan 
   80      nan      nan      nan 
   81      nan      nan      nan 
   82      nan      nan      nan 
   83      nan      nan      nan 
   84      nan      nan      nan 
   85      nan      nan      nan 
   86      nan      nan      nan 
   87      nan      nan      nan 
   88      nan      nan      nan 
   89      nan      nan      nan 
   90      nan      nan      nan 
   91      nan      nan      nan 
   92      nan      nan      nan 
   93      nan      nan      nan 
   94      nan      nan      nan 
   95      nan      nan      nan 
   96      nan      nan      nan 
   97      nan      nan      nan 
   98      nan      nan      nan 
   99      nan      nan      nan 
  100      nan      nan      nan 
  101      nan      nan      nan 
  102      nan      nan      nan 
  103      nan     1.22      3.4 
  104      nan      nan      3.4 
  105      nan      nan      3.4 
  106      nan      nan      3.4 
  107      nan      nan      3.4 
  108      nan      nan      3.4 
  109      nan      nan      3.4 
  110      nan     1.22      nan 
  111      nan     1.22      nan 
  112      nan     1.22      nan 
  113      nan     1.22      nan 
  114      nan     1.22      nan 
  115      nan     1.22      nan 
  116      nan      nan      nan 
  117      nan      nan      nan 
  118      nan      nan      nan 
  119      nan      nan      nan 
  120      nan      nan      nan 
  121      nan      nan      nan 
  122      nan      nan      nan 
  123      nan      nan      nan 
  124      nan      nan      nan 
  125      nan      nan      nan 
  126      nan      nan      nan 
  127      nan      nan      nan 
  128      nan      nan      nan 
  129      nan      nan      nan 
  130      nan      nan      nan 
  131      nan      nan      nan 
  132      nan      nan      nan 
  133      nan      nan      nan 
  134      nan      nan      nan 
  135      nan      nan      nan 
  136      nan      nan      nan 
  137      nan      nan      nan 
  138      nan      nan      nan 
  139      nan     1.22      3.4 
  140      nan      nan      3.4 
  141      nan      nan      3.4 
  142      nan      nan      3.4 
  143      nan      nan      3.4 
  144      nan      nan      3.4 
  145      nan      nan      3.4 
  146      nan     1.22      nan 
  147      nan     1.22      nan 
  148      nan     1.22      nan 
  149      nan     1.22      nan 
  150      nan     1.22      nan 
  151      nan     1.22      nan 
  152      nan      nan      nan 
  153      nan      nan      nan 
  154      nan      nan      nan 
  155      nan      nan      nan 
  156      nan      nan      nan 
  157      nan      nan      nan 
  158      nan      nan      nan 
  159      nan      nan      nan 
  160      nan      nan      nan 
  161      nan      nan      nan 
  162      nan      nan      nan 
  163      nan      nan      nan 
  164      nan      nan      nan 
  165      nan      nan      nan 
  166      nan      nan      nan 
  167      nan      nan      nan 
  168      nan      nan      nan 
  169      nan      nan      nan 
  170      nan      nan      nan 
  171      nan      nan      nan 
  172      nan      nan      nan 
  173      nan      nan      nan 
  174      nan      nan      nan 
  175      nan     1.22      3.4 
  176      nan      nan      3.4 
  177      nan      nan      3.4 
  178      nan      nan      3.4 
  179      nan      nan      3.4 
  180      nan      nan      3.4 
  181      nan      nan      3.4 
  182      nan     1.22      nan 
  183      nan     1.22      nan 
  184      nan     1.22      nan 
  185      nan     1.22      nan 
  186      nan     1.22      nan 
  187      nan     1.22      nan 
  188      nan      nan      nan 
  189      nan      nan      nan 
  190      nan      nan      nan 
  191      nan      nan      nan 
  192      nan      nan      nan 
  193      nan      nan      nan 
  194      nan      nan      nan 
  195      nan      nan      nan 
  196      nan      nan      nan 
  197      nan      nan      nan 
  198      nan      nan      nan 
  199      nan      nan      nan 
  200      nan      nan      nan 
  201      nan      nan      nan 
  202      nan      nan      nan 
  203      nan      nan      nan 
  204      nan      nan      nan 
  205      nan      nan      nan 
  206      nan      nan      nan 
  207      nan      nan      nan 
  208      nan      nan      nan 
  209      nan      nan      nan 
  210      nan      nan      nan 
Function minimum is not valid: <FMin algorithm='Migrad' edm=nan edm_goal=0.0002 errordef=1.0 fval=nan has_accurate_covar=False has_covariance=True has_made_posdef_covar=True has_parameters_at_limit=False has_posdef_covar=False has_reached_call_limit=False has_valid_parameters=False hesse_failed=False is_above_max_edm=True is_valid=False nfcn=240 ngrad=0 reduced_chi2=nan time=-0.0940000000409782>
Fit results:
    a = 1.22 ± nan
    b = 3.4 ± nan
MINOS error estimate not available.
chi^2 = nan, dof = 3, reduced-chi^2 = nan
Traceback (most recent call last):
  File "veusz\windows\consolewindow.py", line 255, in runFunction
  File "veusz\widgets\fit.py", line 407, in actionFit
  File "veusz\document\doc.py", line 204, in applyOperation
  File "veusz\document\operations.py", line 1152, in do
  File "veusz\document\operations.py", line 81, in do
  File "veusz\setting\setting.py", line 129, in set
  File "veusz\setting\setting.py", line 490, in normalize
  File "veusz\setting\setting.py", line 456, in _finiteRangeFloat
veusz.utils.utilfuncs.InvalidType: Finite values only allowed

![figure1](https://github.com/veusz/veusz/assets/72638459/318ea840-05b4-4828-a8a3-8ede7e256c66)
[point data.txt](https://github.com/veusz/veusz/files/13784486/point.data.txt)

**Comment by jeremysanders** [comment]
I think this is because you're doing the fractional power of a negative number. This doesn't seem properly defined.

You're doing

    -0.05223828**3.4

This is a nan value in numpy, which Veusz uses for its arithmetic.
