### ISSUE TITLE
Unable to start ppa ubuntu version

### ISSUE THREAD

**Issue by neutrino82** [veusz/veusz#730]
I have Veusz installed on Ubuntu 22.04 via PPA. I didn't used for a while and now upon trying to start it I get the following errors

> 
> `veusz 
> 
> A module that was compiled using NumPy 1.x cannot be run in
> NumPy 2.1.2 as it may crash. To support both 1.x and 2.x
> versions of NumPy, modules must be compiled with NumPy 2.0.
> Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.
> 
> If you are a user of the module, the easiest solution will be to
> downgrade to 'numpy<2' or try to upgrade the affected module.
> We expect that some modules will need time to support NumPy 2.
> 
> Traceback (most recent call last):  File "/usr/bin/veusz", line 33, in <module>
>     sys.exit(load_entry_point('veusz==3.6.2', 'gui_scripts', 'veusz')())
>   File "/usr/bin/veusz", line 25, in importlib_load_entry_point
>     return next(matches).load()
>   File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
>     module = import_module(match.group('module'))
>   File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "/usr/lib/python3/dist-packages/veusz/veusz_main.py", line 30, in <module>
>     from veusz import utils
>   File "/usr/lib/python3/dist-packages/veusz/utils/__init__.py", line 22, in <module>
>     from .textrender import Renderer, FontMetrics, latexEscape
>   File "/usr/lib/python3/dist-packages/veusz/utils/textrender.py", line 28, in <module>
>     from . import points
>   File "/usr/lib/python3/dist-packages/veusz/utils/points.py", line 24, in <module>
>     from . import colormap
>   File "/usr/lib/python3/dist-packages/veusz/utils/colormap.py", line 24, in <module>
>     from ..helpers.qtloops import numpyToQImage, applyImageTransparancy
> AttributeError: _ARRAY_API not found
> Traceback (most recent call last):
>   File "/usr/bin/veusz", line 33, in <module>
>     sys.exit(load_entry_point('veusz==3.6.2', 'gui_scripts', 'veusz')())
>   File "/usr/bin/veusz", line 25, in importlib_load_entry_point
>     return next(matches).load()
>   File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
>     module = import_module(match.group('module'))
>   File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
>   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
>   File "/usr/lib/python3/dist-packages/veusz/veusz_main.py", line 30, in <module>
>     from veusz import utils
>   File "/usr/lib/python3/dist-packages/veusz/utils/__init__.py", line 22, in <module>
>     from .textrender import Renderer, FontMetrics, latexEscape
>   File "/usr/lib/python3/dist-packages/veusz/utils/textrender.py", line 28, in <module>
>     from . import points
>   File "/usr/lib/python3/dist-packages/veusz/utils/points.py", line 24, in <module>
>     from . import colormap
>   File "/usr/lib/python3/dist-packages/veusz/utils/colormap.py", line 24, in <module>
>     from ..helpers.qtloops import numpyToQImage, applyImageTransparancy
> SystemError: initialization of qtloops raised unreported exception`
> 

Could you help in solving this issues? Thanks

**Comment by neutrino82** [comment]
You were right. Sorry for bothering you. I checked the ubuntu packages but forgot I recently tested some software installed using PIP.  I solved simply with:

>pip install --upgrade numpy==1.26.4

Thank you.
